<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo><!-- setting GenerateAssemblyInfo to false causes this bug https://github.com/dotnet/project-system/issues/3934 -->
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>StripyHorse</AssemblyName>
    <PackageId>StripyHorse</PackageId>
    <OutputType>Library</OutputType>
    <Authors>Stripy Horse</Authors>
    <Company>Stripy Horse</Company>
    <AssemblyTitle>Stripy Horse</AssemblyTitle>
    <Description>Official C# client for the Stripy Horse API - Zebra/ZPL developer tools</Description>
    <Copyright>Copyright 2026 Ben Faerber</Copyright>
    <RootNamespace>StripyHorse</RootNamespace>
    <Version>0.3.0</Version>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\StripyHorse.xml</DocumentationFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Stripy-Horse/stripyhorse-csharp.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>Minor update</PackageReleaseNotes>
    <PackageTags>zebra zpl label printing barcode shipping</PackageTags>
    <Nullable>annotations</Nullable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonSubTypes" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.0.0" />
    <PackageReference Include="Polly" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
