/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using StripyHorse.Client;
using StripyHorse.Model;

namespace StripyHorse.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IComposeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Compose ZPL from typed JSON elements
        /// </summary>
        /// <remarks>
        /// Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ComposeOutputBody</returns>
        ComposeOutputBody ComposeLabel(ComposeInputBody composeInputBody, int operationIndex = 0);

        /// <summary>
        /// Compose ZPL from typed JSON elements
        /// </summary>
        /// <remarks>
        /// Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ComposeOutputBody</returns>
        ApiResponse<ComposeOutputBody> ComposeLabelWithHttpInfo(ComposeInputBody composeInputBody, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IComposeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Compose ZPL from typed JSON elements
        /// </summary>
        /// <remarks>
        /// Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComposeOutputBody</returns>
        System.Threading.Tasks.Task<ComposeOutputBody> ComposeLabelAsync(ComposeInputBody composeInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Compose ZPL from typed JSON elements
        /// </summary>
        /// <remarks>
        /// Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComposeOutputBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<ComposeOutputBody>> ComposeLabelWithHttpInfoAsync(ComposeInputBody composeInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IComposeApi : IComposeApiSync, IComposeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ComposeApi : IComposeApi
    {
        private StripyHorse.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ComposeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ComposeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComposeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ComposeApi(string basePath)
        {
            this.Configuration = StripyHorse.Client.Configuration.MergeConfigurations(
                StripyHorse.Client.GlobalConfiguration.Instance,
                new StripyHorse.Client.Configuration { BasePath = basePath }
            );
            this.Client = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComposeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ComposeApi(StripyHorse.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = StripyHorse.Client.Configuration.MergeConfigurations(
                StripyHorse.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComposeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ComposeApi(StripyHorse.Client.ISynchronousClient client, StripyHorse.Client.IAsynchronousClient asyncClient, StripyHorse.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public StripyHorse.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public StripyHorse.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public StripyHorse.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public StripyHorse.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Compose ZPL from typed JSON elements Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ComposeOutputBody</returns>
        public ComposeOutputBody ComposeLabel(ComposeInputBody composeInputBody, int operationIndex = 0)
        {
            StripyHorse.Client.ApiResponse<ComposeOutputBody> localVarResponse = ComposeLabelWithHttpInfo(composeInputBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Compose ZPL from typed JSON elements Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ComposeOutputBody</returns>
        public StripyHorse.Client.ApiResponse<ComposeOutputBody> ComposeLabelWithHttpInfo(ComposeInputBody composeInputBody, int operationIndex = 0)
        {
            // verify the required parameter 'composeInputBody' is set
            if (composeInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'composeInputBody' when calling ComposeApi->ComposeLabel");
            }

            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = composeInputBody;

            localVarRequestOptions.Operation = "ComposeApi.ComposeLabel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ComposeOutputBody>("/v1/labels/compose", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComposeLabel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Compose ZPL from typed JSON elements Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ComposeOutputBody</returns>
        public async System.Threading.Tasks.Task<ComposeOutputBody> ComposeLabelAsync(ComposeInputBody composeInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            StripyHorse.Client.ApiResponse<ComposeOutputBody> localVarResponse = await ComposeLabelWithHttpInfoAsync(composeInputBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Compose ZPL from typed JSON elements Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="composeInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ComposeOutputBody)</returns>
        public async System.Threading.Tasks.Task<StripyHorse.Client.ApiResponse<ComposeOutputBody>> ComposeLabelWithHttpInfoAsync(ComposeInputBody composeInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'composeInputBody' is set
            if (composeInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'composeInputBody' when calling ComposeApi->ComposeLabel");
            }


            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = composeInputBody;

            localVarRequestOptions.Operation = "ComposeApi.ComposeLabel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ComposeOutputBody>("/v1/labels/compose", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ComposeLabel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
