/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using StripyHorse.Client;
using StripyHorse.Model;

namespace StripyHorse.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrintersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Decode a Zebra ~HS host status response
        /// </summary>
        /// <remarks>
        /// Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HostStatusOutputBody</returns>
        HostStatusOutputBody ParseHostStatus(HostStatusInputBody hostStatusInputBody, int operationIndex = 0);

        /// <summary>
        /// Decode a Zebra ~HS host status response
        /// </summary>
        /// <remarks>
        /// Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HostStatusOutputBody</returns>
        ApiResponse<HostStatusOutputBody> ParseHostStatusWithHttpInfo(HostStatusInputBody hostStatusInputBody, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrintersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Decode a Zebra ~HS host status response
        /// </summary>
        /// <remarks>
        /// Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HostStatusOutputBody</returns>
        System.Threading.Tasks.Task<HostStatusOutputBody> ParseHostStatusAsync(HostStatusInputBody hostStatusInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Decode a Zebra ~HS host status response
        /// </summary>
        /// <remarks>
        /// Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HostStatusOutputBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<HostStatusOutputBody>> ParseHostStatusWithHttpInfoAsync(HostStatusInputBody hostStatusInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrintersApi : IPrintersApiSync, IPrintersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PrintersApi : IPrintersApi
    {
        private StripyHorse.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PrintersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PrintersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrintersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PrintersApi(string basePath)
        {
            this.Configuration = StripyHorse.Client.Configuration.MergeConfigurations(
                StripyHorse.Client.GlobalConfiguration.Instance,
                new StripyHorse.Client.Configuration { BasePath = basePath }
            );
            this.Client = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrintersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PrintersApi(StripyHorse.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = StripyHorse.Client.Configuration.MergeConfigurations(
                StripyHorse.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrintersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PrintersApi(StripyHorse.Client.ISynchronousClient client, StripyHorse.Client.IAsynchronousClient asyncClient, StripyHorse.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public StripyHorse.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public StripyHorse.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public StripyHorse.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public StripyHorse.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Decode a Zebra ~HS host status response Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>HostStatusOutputBody</returns>
        public HostStatusOutputBody ParseHostStatus(HostStatusInputBody hostStatusInputBody, int operationIndex = 0)
        {
            StripyHorse.Client.ApiResponse<HostStatusOutputBody> localVarResponse = ParseHostStatusWithHttpInfo(hostStatusInputBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Decode a Zebra ~HS host status response Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of HostStatusOutputBody</returns>
        public StripyHorse.Client.ApiResponse<HostStatusOutputBody> ParseHostStatusWithHttpInfo(HostStatusInputBody hostStatusInputBody, int operationIndex = 0)
        {
            // verify the required parameter 'hostStatusInputBody' is set
            if (hostStatusInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'hostStatusInputBody' when calling PrintersApi->ParseHostStatus");
            }

            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = hostStatusInputBody;

            localVarRequestOptions.Operation = "PrintersApi.ParseHostStatus";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<HostStatusOutputBody>("/v1/host-status/parse", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ParseHostStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Decode a Zebra ~HS host status response Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of HostStatusOutputBody</returns>
        public async System.Threading.Tasks.Task<HostStatusOutputBody> ParseHostStatusAsync(HostStatusInputBody hostStatusInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            StripyHorse.Client.ApiResponse<HostStatusOutputBody> localVarResponse = await ParseHostStatusWithHttpInfoAsync(hostStatusInputBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Decode a Zebra ~HS host status response Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hostStatusInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (HostStatusOutputBody)</returns>
        public async System.Threading.Tasks.Task<StripyHorse.Client.ApiResponse<HostStatusOutputBody>> ParseHostStatusWithHttpInfoAsync(HostStatusInputBody hostStatusInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'hostStatusInputBody' is set
            if (hostStatusInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'hostStatusInputBody' when calling PrintersApi->ParseHostStatus");
            }


            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = hostStatusInputBody;

            localVarRequestOptions.Operation = "PrintersApi.ParseHostStatus";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<HostStatusOutputBody>("/v1/host-status/parse", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ParseHostStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
