/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using StripyHorse.Client;
using StripyHorse.Model;

namespace StripyHorse.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRenderApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Grade a label&#39;s barcodes before they ship
        /// </summary>
        /// <remarks>
        /// Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PreflightOutputBody</returns>
        PreflightOutputBody PreflightLabel(PreflightInputBody preflightInputBody, int operationIndex = 0);

        /// <summary>
        /// Grade a label&#39;s barcodes before they ship
        /// </summary>
        /// <remarks>
        /// Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PreflightOutputBody</returns>
        ApiResponse<PreflightOutputBody> PreflightLabelWithHttpInfo(PreflightInputBody preflightInputBody, int operationIndex = 0);
        /// <summary>
        /// Render ZPL to PNG images
        /// </summary>
        /// <remarks>
        /// Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RenderOutputBody</returns>
        RenderOutputBody RenderZpl(RenderInputBody renderInputBody, int operationIndex = 0);

        /// <summary>
        /// Render ZPL to PNG images
        /// </summary>
        /// <remarks>
        /// Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RenderOutputBody</returns>
        ApiResponse<RenderOutputBody> RenderZplWithHttpInfo(RenderInputBody renderInputBody, int operationIndex = 0);
        /// <summary>
        /// Render ZPL and return the first label as a raw PNG
        /// </summary>
        /// <remarks>
        /// curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>string</returns>
        string RenderZplPng(RenderInputBody renderInputBody, int operationIndex = 0);

        /// <summary>
        /// Render ZPL and return the first label as a raw PNG
        /// </summary>
        /// <remarks>
        /// curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> RenderZplPngWithHttpInfo(RenderInputBody renderInputBody, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRenderApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Grade a label&#39;s barcodes before they ship
        /// </summary>
        /// <remarks>
        /// Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PreflightOutputBody</returns>
        System.Threading.Tasks.Task<PreflightOutputBody> PreflightLabelAsync(PreflightInputBody preflightInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Grade a label&#39;s barcodes before they ship
        /// </summary>
        /// <remarks>
        /// Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PreflightOutputBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<PreflightOutputBody>> PreflightLabelWithHttpInfoAsync(PreflightInputBody preflightInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Render ZPL to PNG images
        /// </summary>
        /// <remarks>
        /// Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RenderOutputBody</returns>
        System.Threading.Tasks.Task<RenderOutputBody> RenderZplAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Render ZPL to PNG images
        /// </summary>
        /// <remarks>
        /// Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RenderOutputBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<RenderOutputBody>> RenderZplWithHttpInfoAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Render ZPL and return the first label as a raw PNG
        /// </summary>
        /// <remarks>
        /// curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> RenderZplPngAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Render ZPL and return the first label as a raw PNG
        /// </summary>
        /// <remarks>
        /// curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </remarks>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> RenderZplPngWithHttpInfoAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRenderApi : IRenderApiSync, IRenderApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RenderApi : IRenderApi
    {
        private StripyHorse.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RenderApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RenderApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RenderApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RenderApi(string basePath)
        {
            this.Configuration = StripyHorse.Client.Configuration.MergeConfigurations(
                StripyHorse.Client.GlobalConfiguration.Instance,
                new StripyHorse.Client.Configuration { BasePath = basePath }
            );
            this.Client = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RenderApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RenderApi(StripyHorse.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = StripyHorse.Client.Configuration.MergeConfigurations(
                StripyHorse.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new StripyHorse.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RenderApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RenderApi(StripyHorse.Client.ISynchronousClient client, StripyHorse.Client.IAsynchronousClient asyncClient, StripyHorse.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = StripyHorse.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public StripyHorse.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public StripyHorse.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public StripyHorse.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public StripyHorse.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Grade a label&#39;s barcodes before they ship Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PreflightOutputBody</returns>
        public PreflightOutputBody PreflightLabel(PreflightInputBody preflightInputBody, int operationIndex = 0)
        {
            StripyHorse.Client.ApiResponse<PreflightOutputBody> localVarResponse = PreflightLabelWithHttpInfo(preflightInputBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Grade a label&#39;s barcodes before they ship Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PreflightOutputBody</returns>
        public StripyHorse.Client.ApiResponse<PreflightOutputBody> PreflightLabelWithHttpInfo(PreflightInputBody preflightInputBody, int operationIndex = 0)
        {
            // verify the required parameter 'preflightInputBody' is set
            if (preflightInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'preflightInputBody' when calling RenderApi->PreflightLabel");
            }

            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = preflightInputBody;

            localVarRequestOptions.Operation = "RenderApi.PreflightLabel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PreflightOutputBody>("/v1/preflight", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PreflightLabel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Grade a label&#39;s barcodes before they ship Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PreflightOutputBody</returns>
        public async System.Threading.Tasks.Task<PreflightOutputBody> PreflightLabelAsync(PreflightInputBody preflightInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            StripyHorse.Client.ApiResponse<PreflightOutputBody> localVarResponse = await PreflightLabelWithHttpInfoAsync(preflightInputBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Grade a label&#39;s barcodes before they ship Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="preflightInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PreflightOutputBody)</returns>
        public async System.Threading.Tasks.Task<StripyHorse.Client.ApiResponse<PreflightOutputBody>> PreflightLabelWithHttpInfoAsync(PreflightInputBody preflightInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'preflightInputBody' is set
            if (preflightInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'preflightInputBody' when calling RenderApi->PreflightLabel");
            }


            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = preflightInputBody;

            localVarRequestOptions.Operation = "RenderApi.PreflightLabel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PreflightOutputBody>("/v1/preflight", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PreflightLabel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Render ZPL to PNG images Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RenderOutputBody</returns>
        public RenderOutputBody RenderZpl(RenderInputBody renderInputBody, int operationIndex = 0)
        {
            StripyHorse.Client.ApiResponse<RenderOutputBody> localVarResponse = RenderZplWithHttpInfo(renderInputBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Render ZPL to PNG images Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RenderOutputBody</returns>
        public StripyHorse.Client.ApiResponse<RenderOutputBody> RenderZplWithHttpInfo(RenderInputBody renderInputBody, int operationIndex = 0)
        {
            // verify the required parameter 'renderInputBody' is set
            if (renderInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'renderInputBody' when calling RenderApi->RenderZpl");
            }

            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = renderInputBody;

            localVarRequestOptions.Operation = "RenderApi.RenderZpl";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<RenderOutputBody>("/v1/render", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RenderZpl", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Render ZPL to PNG images Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RenderOutputBody</returns>
        public async System.Threading.Tasks.Task<RenderOutputBody> RenderZplAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            StripyHorse.Client.ApiResponse<RenderOutputBody> localVarResponse = await RenderZplWithHttpInfoAsync(renderInputBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Render ZPL to PNG images Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RenderOutputBody)</returns>
        public async System.Threading.Tasks.Task<StripyHorse.Client.ApiResponse<RenderOutputBody>> RenderZplWithHttpInfoAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'renderInputBody' is set
            if (renderInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'renderInputBody' when calling RenderApi->RenderZpl");
            }


            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = renderInputBody;

            localVarRequestOptions.Operation = "RenderApi.RenderZpl";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<RenderOutputBody>("/v1/render", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RenderZpl", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Render ZPL and return the first label as a raw PNG curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>string</returns>
        public string RenderZplPng(RenderInputBody renderInputBody, int operationIndex = 0)
        {
            StripyHorse.Client.ApiResponse<string> localVarResponse = RenderZplPngWithHttpInfo(renderInputBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Render ZPL and return the first label as a raw PNG curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of string</returns>
        public StripyHorse.Client.ApiResponse<string> RenderZplPngWithHttpInfo(RenderInputBody renderInputBody, int operationIndex = 0)
        {
            // verify the required parameter 'renderInputBody' is set
            if (renderInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'renderInputBody' when calling RenderApi->RenderZplPng");
            }

            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = renderInputBody;

            localVarRequestOptions.Operation = "RenderApi.RenderZplPng";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<string>("/v1/render.png", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RenderZplPng", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Render ZPL and return the first label as a raw PNG curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> RenderZplPngAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            StripyHorse.Client.ApiResponse<string> localVarResponse = await RenderZplPngWithHttpInfoAsync(renderInputBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Render ZPL and return the first label as a raw PNG curl-friendly variant: the X-Label-Count response header carries the total label count.
        /// </summary>
        /// <exception cref="StripyHorse.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="renderInputBody"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<StripyHorse.Client.ApiResponse<string>> RenderZplPngWithHttpInfoAsync(RenderInputBody renderInputBody, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'renderInputBody' is set
            if (renderInputBody == null)
            {
                throw new StripyHorse.Client.ApiException(400, "Missing required parameter 'renderInputBody' when calling RenderApi->RenderZplPng");
            }


            StripyHorse.Client.RequestOptions localVarRequestOptions = new StripyHorse.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = StripyHorse.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = StripyHorse.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = renderInputBody;

            localVarRequestOptions.Operation = "RenderApi.RenderZplPng";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (headerKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Api-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-Api-Key", this.Configuration.GetApiKeyWithPrefix("X-Api-Key"));
            }
            // authentication (bearerKey) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<string>("/v1/render.png", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RenderZplPng", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
