/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using StripyHorse.Client;
using StripyHorse.Api;
// uncomment below to import models
//using StripyHorse.Model;

namespace StripyHorse.Test.Api
{
    /// <summary>
    ///  Class for testing ComposeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ComposeApiTests : IDisposable
    {
        private ComposeApi instance;

        public ComposeApiTests()
        {
            instance = new ComposeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComposeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ComposeApi
            //Assert.IsType<ComposeApi>(instance);
        }

        /// <summary>
        /// Test ComposeLabel
        /// </summary>
        [Fact]
        public void ComposeLabelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ComposeInputBody composeInputBody = null;
            //var response = instance.ComposeLabel(composeInputBody);
            //Assert.IsType<ComposeOutputBody>(response);
        }
    }
}
