/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using StripyHorse.Client;
using StripyHorse.Api;
// uncomment below to import models
//using StripyHorse.Model;

namespace StripyHorse.Test.Api
{
    /// <summary>
    ///  Class for testing ConvertApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConvertApiTests : IDisposable
    {
        private ConvertApi instance;

        public ConvertApiTests()
        {
            instance = new ConvertApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConvertApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConvertApi
            //Assert.IsType<ConvertApi>(instance);
        }

        /// <summary>
        /// Test ConvertBatch
        /// </summary>
        [Fact]
        public void ConvertBatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<System.IO.Stream> files = null;
            //bool? barcodeAware = null;
            //string? compression = null;
            //long? dpmm = null;
            //double? heightMm = null;
            //string? preset = null;
            //long? rotation = null;
            //string? scale = null;
            //long? threshold = null;
            //double? widthMm = null;
            //instance.ConvertBatch(files, barcodeAware, compression, dpmm, heightMm, preset, rotation, scale, threshold, widthMm);
        }

        /// <summary>
        /// Test ConvertDocument
        /// </summary>
        [Fact]
        public void ConvertDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //bool? barcodeAware = null;
            //string? compression = null;
            //long? dpmm = null;
            //double? heightMm = null;
            //string? preset = null;
            //long? rotation = null;
            //string? scale = null;
            //long? threshold = null;
            //double? widthMm = null;
            //var response = instance.ConvertDocument(file, barcodeAware, compression, dpmm, heightMm, preset, rotation, scale, threshold, widthMm);
            //Assert.IsType<ConvertOutputBody>(response);
        }

        /// <summary>
        /// Test ConvertHtml
        /// </summary>
        [Fact]
        public void ConvertHtmlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HtmlInputBody htmlInputBody = null;
            //var response = instance.ConvertHtml(htmlInputBody);
            //Assert.IsType<HtmlOutputBody>(response);
        }

        /// <summary>
        /// Test ConvertZplToHtml
        /// </summary>
        [Fact]
        public void ConvertZplToHtmlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ZplHTMLInputBody zplHTMLInputBody = null;
            //var response = instance.ConvertZplToHtml(zplHTMLInputBody);
            //Assert.IsType<ZplHTMLOutputBody>(response);
        }

        /// <summary>
        /// Test RasterizeUnicode
        /// </summary>
        [Fact]
        public void RasterizeUnicodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UnicodeInputBody unicodeInputBody = null;
            //var response = instance.RasterizeUnicode(unicodeInputBody);
            //Assert.IsType<UnicodeOutputBody>(response);
        }

        /// <summary>
        /// Test StampZpl
        /// </summary>
        [Fact]
        public void StampZplTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //StampInputBody stampInputBody = null;
            //var response = instance.StampZpl(stampInputBody);
            //Assert.IsType<StampOutputBody>(response);
        }

        /// <summary>
        /// Test VoidZpl
        /// </summary>
        [Fact]
        public void VoidZplTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VoidInputBody voidInputBody = null;
            //var response = instance.VoidZpl(voidInputBody);
            //Assert.IsType<VoidOutputBody>(response);
        }
    }
}
