/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using StripyHorse.Client;
using StripyHorse.Api;
// uncomment below to import models
//using StripyHorse.Model;

namespace StripyHorse.Test.Api
{
    /// <summary>
    ///  Class for testing RenderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RenderApiTests : IDisposable
    {
        private RenderApi instance;

        public RenderApiTests()
        {
            instance = new RenderApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenderApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RenderApi
            //Assert.IsType<RenderApi>(instance);
        }

        /// <summary>
        /// Test PreflightLabel
        /// </summary>
        [Fact]
        public void PreflightLabelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PreflightInputBody preflightInputBody = null;
            //var response = instance.PreflightLabel(preflightInputBody);
            //Assert.IsType<PreflightOutputBody>(response);
        }

        /// <summary>
        /// Test RenderZpl
        /// </summary>
        [Fact]
        public void RenderZplTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RenderInputBody renderInputBody = null;
            //var response = instance.RenderZpl(renderInputBody);
            //Assert.IsType<RenderOutputBody>(response);
        }

        /// <summary>
        /// Test RenderZplPng
        /// </summary>
        [Fact]
        public void RenderZplPngTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RenderInputBody renderInputBody = null;
            //var response = instance.RenderZplPng(renderInputBody);
            //Assert.IsType<string>(response);
        }
    }
}
