/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using StripyHorse.Client;
using StripyHorse.Api;
// uncomment below to import models
//using StripyHorse.Model;

namespace StripyHorse.Test.Api
{
    /// <summary>
    ///  Class for testing SimulatorApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SimulatorApiTests : IDisposable
    {
        private SimulatorApi instance;

        public SimulatorApiTests()
        {
            instance = new SimulatorApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimulatorApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SimulatorApi
            //Assert.IsType<SimulatorApi>(instance);
        }

        /// <summary>
        /// Test ClearJobs
        /// </summary>
        [Fact]
        public void ClearJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //instance.ClearJobs(printerId);
        }

        /// <summary>
        /// Test CreatePrinter
        /// </summary>
        [Fact]
        public void CreatePrinterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePrinterInputBody createPrinterInputBody = null;
            //var response = instance.CreatePrinter(createPrinterInputBody);
            //Assert.IsType<PrinterBody>(response);
        }

        /// <summary>
        /// Test DeleteJob
        /// </summary>
        [Fact]
        public void DeleteJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //long jobId = null;
            //instance.DeleteJob(printerId, jobId);
        }

        /// <summary>
        /// Test DeletePrinter
        /// </summary>
        [Fact]
        public void DeletePrinterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //instance.DeletePrinter(printerId);
        }

        /// <summary>
        /// Test GetJob
        /// </summary>
        [Fact]
        public void GetJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //long jobId = null;
            //var response = instance.GetJob(printerId, jobId);
            //Assert.IsType<JobOutputBody>(response);
        }

        /// <summary>
        /// Test GetJobLabel
        /// </summary>
        [Fact]
        public void GetJobLabelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //long jobId = null;
            //long index = null;
            //var response = instance.GetJobLabel(printerId, jobId, index);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test GetPrinter
        /// </summary>
        [Fact]
        public void GetPrinterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //var response = instance.GetPrinter(printerId);
            //Assert.IsType<PrinterBody>(response);
        }

        /// <summary>
        /// Test ListJobs
        /// </summary>
        [Fact]
        public void ListJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //long? limit = null;
            //long? before = null;
            //var response = instance.ListJobs(printerId, limit, before);
            //Assert.IsType<ListJobsOutputBody>(response);
        }

        /// <summary>
        /// Test ListPrinters
        /// </summary>
        [Fact]
        public void ListPrintersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListPrinters();
            //Assert.IsType<ListPrintersOutputBody>(response);
        }

        /// <summary>
        /// Test LoadPrinterMedia
        /// </summary>
        [Fact]
        public void LoadPrinterMediaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //MediaInputBody mediaInputBody = null;
            //var response = instance.LoadPrinterMedia(printerId, mediaInputBody);
            //Assert.IsType<StateOutputBody>(response);
        }

        /// <summary>
        /// Test ResetPrinter
        /// </summary>
        [Fact]
        public void ResetPrinterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //var response = instance.ResetPrinter(printerId);
            //Assert.IsType<StateOutputBody>(response);
        }

        /// <summary>
        /// Test SetPrinterFaults
        /// </summary>
        [Fact]
        public void SetPrinterFaultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //Faults faults = null;
            //var response = instance.SetPrinterFaults(printerId, faults);
            //Assert.IsType<StateOutputBody>(response);
        }

        /// <summary>
        /// Test UpdatePrinter
        /// </summary>
        [Fact]
        public void UpdatePrinterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string printerId = null;
            //UpdatePrinterInputBody updatePrinterInputBody = null;
            //var response = instance.UpdatePrinter(printerId, updatePrinterInputBody);
            //Assert.IsType<PrinterBody>(response);
        }
    }
}
