/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing Barcode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BarcodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Barcode
        //private Barcode instance;

        public BarcodeTests()
        {
            // TODO uncomment below to create an instance of Barcode
            //instance = new Barcode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Barcode
        /// </summary>
        [Fact]
        public void BarcodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Barcode
            //Assert.IsType<Barcode>(instance);
        }

        /// <summary>
        /// Test the property 'BlurMarginDots'
        /// </summary>
        [Fact]
        public void BlurMarginDotsTest()
        {
            // TODO unit test for the property 'BlurMarginDots'
        }

        /// <summary>
        /// Test the property 'Checks'
        /// </summary>
        [Fact]
        public void ChecksTest()
        {
            // TODO unit test for the property 'Checks'
        }

        /// <summary>
        /// Test the property 'CrossDpi'
        /// </summary>
        [Fact]
        public void CrossDpiTest()
        {
            // TODO unit test for the property 'CrossDpi'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'ModuleDots'
        /// </summary>
        [Fact]
        public void ModuleDotsTest()
        {
            // TODO unit test for the property 'ModuleDots'
        }

        /// <summary>
        /// Test the property 'QuietLeftModules'
        /// </summary>
        [Fact]
        public void QuietLeftModulesTest()
        {
            // TODO unit test for the property 'QuietLeftModules'
        }

        /// <summary>
        /// Test the property 'QuietRightModules'
        /// </summary>
        [Fact]
        public void QuietRightModulesTest()
        {
            // TODO unit test for the property 'QuietRightModules'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'XDimensionMm'
        /// </summary>
        [Fact]
        public void XDimensionMmTest()
        {
            // TODO unit test for the property 'XDimensionMm'
        }
    }
}
