/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing ConvertOutputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConvertOutputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConvertOutputBody
        //private ConvertOutputBody instance;

        public ConvertOutputBodyTests()
        {
            // TODO uncomment below to create an instance of ConvertOutputBody
            //instance = new ConvertOutputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConvertOutputBody
        /// </summary>
        [Fact]
        public void ConvertOutputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConvertOutputBody
            //Assert.IsType<ConvertOutputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Fact]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }
    }
}
