/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing ConvertedPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConvertedPageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConvertedPage
        //private ConvertedPage instance;

        public ConvertedPageTests()
        {
            // TODO uncomment below to create an instance of ConvertedPage
            //instance = new ConvertedPage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConvertedPage
        /// </summary>
        [Fact]
        public void ConvertedPageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConvertedPage
            //Assert.IsType<ConvertedPage>(instance);
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'Zpl'
        /// </summary>
        [Fact]
        public void ZplTest()
        {
            // TODO unit test for the property 'Zpl'
        }
    }
}
