/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing DPIVerdict
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DPIVerdictTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DPIVerdict
        //private DPIVerdict instance;

        public DPIVerdictTests()
        {
            // TODO uncomment below to create an instance of DPIVerdict
            //instance = new DPIVerdict();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DPIVerdict
        /// </summary>
        [Fact]
        public void DPIVerdictInstanceTest()
        {
            // TODO uncomment below to test "IsType" DPIVerdict
            //Assert.IsType<DPIVerdict>(instance);
        }

        /// <summary>
        /// Test the property 'Dpmm'
        /// </summary>
        [Fact]
        public void DpmmTest()
        {
            // TODO unit test for the property 'Dpmm'
        }

        /// <summary>
        /// Test the property 'Ok'
        /// </summary>
        [Fact]
        public void OkTest()
        {
            // TODO unit test for the property 'Ok'
        }

        /// <summary>
        /// Test the property 'XDimensionMm'
        /// </summary>
        [Fact]
        public void XDimensionMmTest()
        {
            // TODO unit test for the property 'XDimensionMm'
        }
    }
}
