/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing Faults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FaultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Faults
        //private Faults instance;

        public FaultsTests()
        {
            // TODO uncomment below to create an instance of Faults
            //instance = new Faults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Faults
        /// </summary>
        [Fact]
        public void FaultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Faults
            //Assert.IsType<Faults>(instance);
        }

        /// <summary>
        /// Test the property 'HeadUp'
        /// </summary>
        [Fact]
        public void HeadUpTest()
        {
            // TODO unit test for the property 'HeadUp'
        }

        /// <summary>
        /// Test the property 'OverTemp'
        /// </summary>
        [Fact]
        public void OverTempTest()
        {
            // TODO unit test for the property 'OverTemp'
        }

        /// <summary>
        /// Test the property 'PaperOut'
        /// </summary>
        [Fact]
        public void PaperOutTest()
        {
            // TODO unit test for the property 'PaperOut'
        }

        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Fact]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }

        /// <summary>
        /// Test the property 'RibbonOut'
        /// </summary>
        [Fact]
        public void RibbonOutTest()
        {
            // TODO unit test for the property 'RibbonOut'
        }

        /// <summary>
        /// Test the property 'UnderTemp'
        /// </summary>
        [Fact]
        public void UnderTempTest()
        {
            // TODO unit test for the property 'UnderTemp'
        }
    }
}
