/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing HostStatusInputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostStatusInputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostStatusInputBody
        //private HostStatusInputBody instance;

        public HostStatusInputBodyTests()
        {
            // TODO uncomment below to create an instance of HostStatusInputBody
            //instance = new HostStatusInputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostStatusInputBody
        /// </summary>
        [Fact]
        public void HostStatusInputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" HostStatusInputBody
            //Assert.IsType<HostStatusInputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
    }
}
