/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing HostStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostStatus
        //private HostStatus instance;

        public HostStatusTests()
        {
            // TODO uncomment below to create an instance of HostStatus
            //instance = new HostStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostStatus
        /// </summary>
        [Fact]
        public void HostStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" HostStatus
            //Assert.IsType<HostStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Blocking'
        /// </summary>
        [Fact]
        public void BlockingTest()
        {
            // TODO unit test for the property 'Blocking'
        }

        /// <summary>
        /// Test the property 'BufferFull'
        /// </summary>
        [Fact]
        public void BufferFullTest()
        {
            // TODO unit test for the property 'BufferFull'
        }

        /// <summary>
        /// Test the property 'CommSettings'
        /// </summary>
        [Fact]
        public void CommSettingsTest()
        {
            // TODO unit test for the property 'CommSettings'
        }

        /// <summary>
        /// Test the property 'CorruptRam'
        /// </summary>
        [Fact]
        public void CorruptRamTest()
        {
            // TODO unit test for the property 'CorruptRam'
        }

        /// <summary>
        /// Test the property 'DiagnosticMode'
        /// </summary>
        [Fact]
        public void DiagnosticModeTest()
        {
            // TODO unit test for the property 'DiagnosticMode'
        }

        /// <summary>
        /// Test the property 'FormatsInBuffer'
        /// </summary>
        [Fact]
        public void FormatsInBufferTest()
        {
            // TODO unit test for the property 'FormatsInBuffer'
        }

        /// <summary>
        /// Test the property 'FunctionSettings'
        /// </summary>
        [Fact]
        public void FunctionSettingsTest()
        {
            // TODO unit test for the property 'FunctionSettings'
        }

        /// <summary>
        /// Test the property 'GraphicsStored'
        /// </summary>
        [Fact]
        public void GraphicsStoredTest()
        {
            // TODO unit test for the property 'GraphicsStored'
        }

        /// <summary>
        /// Test the property 'HeadUp'
        /// </summary>
        [Fact]
        public void HeadUpTest()
        {
            // TODO unit test for the property 'HeadUp'
        }

        /// <summary>
        /// Test the property 'LabelLengthDots'
        /// </summary>
        [Fact]
        public void LabelLengthDotsTest()
        {
            // TODO unit test for the property 'LabelLengthDots'
        }

        /// <summary>
        /// Test the property 'LabelsRemaining'
        /// </summary>
        [Fact]
        public void LabelsRemainingTest()
        {
            // TODO unit test for the property 'LabelsRemaining'
        }

        /// <summary>
        /// Test the property 'OverTemp'
        /// </summary>
        [Fact]
        public void OverTempTest()
        {
            // TODO unit test for the property 'OverTemp'
        }

        /// <summary>
        /// Test the property 'PaperOut'
        /// </summary>
        [Fact]
        public void PaperOutTest()
        {
            // TODO unit test for the property 'PaperOut'
        }

        /// <summary>
        /// Test the property 'PartialFormat'
        /// </summary>
        [Fact]
        public void PartialFormatTest()
        {
            // TODO unit test for the property 'PartialFormat'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Paused'
        /// </summary>
        [Fact]
        public void PausedTest()
        {
            // TODO unit test for the property 'Paused'
        }

        /// <summary>
        /// Test the property 'PrintMode'
        /// </summary>
        [Fact]
        public void PrintModeTest()
        {
            // TODO unit test for the property 'PrintMode'
        }

        /// <summary>
        /// Test the property 'RibbonOut'
        /// </summary>
        [Fact]
        public void RibbonOutTest()
        {
            // TODO unit test for the property 'RibbonOut'
        }

        /// <summary>
        /// Test the property 'StaticRam'
        /// </summary>
        [Fact]
        public void StaticRamTest()
        {
            // TODO unit test for the property 'StaticRam'
        }

        /// <summary>
        /// Test the property 'ThermalTransfer'
        /// </summary>
        [Fact]
        public void ThermalTransferTest()
        {
            // TODO unit test for the property 'ThermalTransfer'
        }

        /// <summary>
        /// Test the property 'UnderTemp'
        /// </summary>
        [Fact]
        public void UnderTempTest()
        {
            // TODO unit test for the property 'UnderTemp'
        }
    }
}
