/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing JobSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobSummary
        //private JobSummary instance;

        public JobSummaryTests()
        {
            // TODO uncomment below to create an instance of JobSummary
            //instance = new JobSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobSummary
        /// </summary>
        [Fact]
        public void JobSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobSummary
            //Assert.IsType<JobSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'LabelCount'
        /// </summary>
        [Fact]
        public void LabelCountTest()
        {
            // TODO unit test for the property 'LabelCount'
        }

        /// <summary>
        /// Test the property 'ReceivedAt'
        /// </summary>
        [Fact]
        public void ReceivedAtTest()
        {
            // TODO unit test for the property 'ReceivedAt'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ZplBytes'
        /// </summary>
        [Fact]
        public void ZplBytesTest()
        {
            // TODO unit test for the property 'ZplBytes'
        }
    }
}
