/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing ListPrintersOutputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPrintersOutputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPrintersOutputBody
        //private ListPrintersOutputBody instance;

        public ListPrintersOutputBodyTests()
        {
            // TODO uncomment below to create an instance of ListPrintersOutputBody
            //instance = new ListPrintersOutputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPrintersOutputBody
        /// </summary>
        [Fact]
        public void ListPrintersOutputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPrintersOutputBody
            //Assert.IsType<ListPrintersOutputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Printers'
        /// </summary>
        [Fact]
        public void PrintersTest()
        {
            // TODO unit test for the property 'Printers'
        }
    }
}
