/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing PreflightOutputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreflightOutputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreflightOutputBody
        //private PreflightOutputBody instance;

        public PreflightOutputBodyTests()
        {
            // TODO uncomment below to create an instance of PreflightOutputBody
            //instance = new PreflightOutputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreflightOutputBody
        /// </summary>
        [Fact]
        public void PreflightOutputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PreflightOutputBody
            //Assert.IsType<PreflightOutputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'Lint'
        /// </summary>
        [Fact]
        public void LintTest()
        {
            // TODO unit test for the property 'Lint'
        }
    }
}
