/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing PrinterBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinterBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrinterBody
        //private PrinterBody instance;

        public PrinterBodyTests()
        {
            // TODO uncomment below to create an instance of PrinterBody
            //instance = new PrinterBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrinterBody
        /// </summary>
        [Fact]
        public void PrinterBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrinterBody
            //Assert.IsType<PrinterBody>(instance);
        }

        /// <summary>
        /// Test the property 'Anonymize'
        /// </summary>
        [Fact]
        public void AnonymizeTest()
        {
            // TODO unit test for the property 'Anonymize'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Dpmm'
        /// </summary>
        [Fact]
        public void DpmmTest()
        {
            // TODO unit test for the property 'Dpmm'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'HeightMm'
        /// </summary>
        [Fact]
        public void HeightMmTest()
        {
            // TODO unit test for the property 'HeightMm'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IngestUrl'
        /// </summary>
        [Fact]
        public void IngestUrlTest()
        {
            // TODO unit test for the property 'IngestUrl'
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Tcp'
        /// </summary>
        [Fact]
        public void TcpTest()
        {
            // TODO unit test for the property 'Tcp'
        }

        /// <summary>
        /// Test the property 'WebhookSecret'
        /// </summary>
        [Fact]
        public void WebhookSecretTest()
        {
            // TODO unit test for the property 'WebhookSecret'
        }

        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }

        /// <summary>
        /// Test the property 'WidthMm'
        /// </summary>
        [Fact]
        public void WidthMmTest()
        {
            // TODO unit test for the property 'WidthMm'
        }
    }
}
