/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing PrinterBodyTCPStruct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrinterBodyTCPStructTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrinterBodyTCPStruct
        //private PrinterBodyTCPStruct instance;

        public PrinterBodyTCPStructTests()
        {
            // TODO uncomment below to create an instance of PrinterBodyTCPStruct
            //instance = new PrinterBodyTCPStruct();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrinterBodyTCPStruct
        /// </summary>
        [Fact]
        public void PrinterBodyTCPStructInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrinterBodyTCPStruct
            //Assert.IsType<PrinterBodyTCPStruct>(instance);
        }

        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
    }
}
