/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing RenderedLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenderedLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenderedLabel
        //private RenderedLabel instance;

        public RenderedLabelTests()
        {
            // TODO uncomment below to create an instance of RenderedLabel
            //instance = new RenderedLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenderedLabel
        /// </summary>
        [Fact]
        public void RenderedLabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenderedLabel
            //Assert.IsType<RenderedLabel>(instance);
        }

        /// <summary>
        /// Test the property 'HeightPx'
        /// </summary>
        [Fact]
        public void HeightPxTest()
        {
            // TODO unit test for the property 'HeightPx'
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Png'
        /// </summary>
        [Fact]
        public void PngTest()
        {
            // TODO unit test for the property 'Png'
        }

        /// <summary>
        /// Test the property 'WidthPx'
        /// </summary>
        [Fact]
        public void WidthPxTest()
        {
            // TODO unit test for the property 'WidthPx'
        }
    }
}
