/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing StatusSnapshot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusSnapshotTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatusSnapshot
        //private StatusSnapshot instance;

        public StatusSnapshotTests()
        {
            // TODO uncomment below to create an instance of StatusSnapshot
            //instance = new StatusSnapshot();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatusSnapshot
        /// </summary>
        [Fact]
        public void StatusSnapshotInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatusSnapshot
            //Assert.IsType<StatusSnapshot>(instance);
        }

        /// <summary>
        /// Test the property 'Faults'
        /// </summary>
        [Fact]
        public void FaultsTest()
        {
            // TODO unit test for the property 'Faults'
        }

        /// <summary>
        /// Test the property 'FormatsInBuffer'
        /// </summary>
        [Fact]
        public void FormatsInBufferTest()
        {
            // TODO unit test for the property 'FormatsInBuffer'
        }

        /// <summary>
        /// Test the property 'LabelLengthDots'
        /// </summary>
        [Fact]
        public void LabelLengthDotsTest()
        {
            // TODO unit test for the property 'LabelLengthDots'
        }

        /// <summary>
        /// Test the property 'Odometer'
        /// </summary>
        [Fact]
        public void OdometerTest()
        {
            // TODO unit test for the property 'Odometer'
        }

        /// <summary>
        /// Test the property 'WidthDots'
        /// </summary>
        [Fact]
        public void WidthDotsTest()
        {
            // TODO unit test for the property 'WidthDots'
        }
    }
}
