/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing StatusField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatusField
        //private StatusField instance;

        public StatusFieldTests()
        {
            // TODO uncomment below to create an instance of StatusField
            //instance = new StatusField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatusField
        /// </summary>
        [Fact]
        public void StatusFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatusField
            //Assert.IsType<StatusField>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Raw'
        /// </summary>
        [Fact]
        public void RawTest()
        {
            // TODO unit test for the property 'Raw'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
