/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing Supplies
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuppliesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Supplies
        //private Supplies instance;

        public SuppliesTests()
        {
            // TODO uncomment below to create an instance of Supplies
            //instance = new Supplies();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Supplies
        /// </summary>
        [Fact]
        public void SuppliesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Supplies
            //Assert.IsType<Supplies>(instance);
        }

        /// <summary>
        /// Test the property 'LabelsLeft'
        /// </summary>
        [Fact]
        public void LabelsLeftTest()
        {
            // TODO unit test for the property 'LabelsLeft'
        }

        /// <summary>
        /// Test the property 'LabelsLoaded'
        /// </summary>
        [Fact]
        public void LabelsLoadedTest()
        {
            // TODO unit test for the property 'LabelsLoaded'
        }

        /// <summary>
        /// Test the property 'RibbonMmLeft'
        /// </summary>
        [Fact]
        public void RibbonMmLeftTest()
        {
            // TODO unit test for the property 'RibbonMmLeft'
        }

        /// <summary>
        /// Test the property 'RibbonMmLoaded'
        /// </summary>
        [Fact]
        public void RibbonMmLoadedTest()
        {
            // TODO unit test for the property 'RibbonMmLoaded'
        }
    }
}
