/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing UnicodeOutputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnicodeOutputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnicodeOutputBody
        //private UnicodeOutputBody instance;

        public UnicodeOutputBodyTests()
        {
            // TODO uncomment below to create an instance of UnicodeOutputBody
            //instance = new UnicodeOutputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnicodeOutputBody
        /// </summary>
        [Fact]
        public void UnicodeOutputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnicodeOutputBody
            //Assert.IsType<UnicodeOutputBody>(instance);
        }

        /// <summary>
        /// Test the property 'FieldsRasterized'
        /// </summary>
        [Fact]
        public void FieldsRasterizedTest()
        {
            // TODO unit test for the property 'FieldsRasterized'
        }

        /// <summary>
        /// Test the property 'Skipped'
        /// </summary>
        [Fact]
        public void SkippedTest()
        {
            // TODO unit test for the property 'Skipped'
        }

        /// <summary>
        /// Test the property 'Zpl'
        /// </summary>
        [Fact]
        public void ZplTest()
        {
            // TODO unit test for the property 'Zpl'
        }
    }
}
