/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing UpdatePrinterInputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdatePrinterInputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdatePrinterInputBody
        //private UpdatePrinterInputBody instance;

        public UpdatePrinterInputBodyTests()
        {
            // TODO uncomment below to create an instance of UpdatePrinterInputBody
            //instance = new UpdatePrinterInputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdatePrinterInputBody
        /// </summary>
        [Fact]
        public void UpdatePrinterInputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdatePrinterInputBody
            //Assert.IsType<UpdatePrinterInputBody>(instance);
        }

        /// <summary>
        /// Test the property 'AccessMode'
        /// </summary>
        [Fact]
        public void AccessModeTest()
        {
            // TODO unit test for the property 'AccessMode'
        }

        /// <summary>
        /// Test the property 'Anonymize'
        /// </summary>
        [Fact]
        public void AnonymizeTest()
        {
            // TODO unit test for the property 'Anonymize'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'WebhookUrl'
        /// </summary>
        [Fact]
        public void WebhookUrlTest()
        {
            // TODO unit test for the property 'WebhookUrl'
        }
    }
}
