/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StripyHorse.Model;
using StripyHorse.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StripyHorse.Test.Model
{
    /// <summary>
    ///  Class for testing VoidInputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VoidInputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VoidInputBody
        //private VoidInputBody instance;

        public VoidInputBodyTests()
        {
            // TODO uncomment below to create an instance of VoidInputBody
            //instance = new VoidInputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VoidInputBody
        /// </summary>
        [Fact]
        public void VoidInputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" VoidInputBody
            //Assert.IsType<VoidInputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Dpmm'
        /// </summary>
        [Fact]
        public void DpmmTest()
        {
            // TODO unit test for the property 'Dpmm'
        }

        /// <summary>
        /// Test the property 'HeightMm'
        /// </summary>
        [Fact]
        public void HeightMmTest()
        {
            // TODO unit test for the property 'HeightMm'
        }

        /// <summary>
        /// Test the property 'Preset'
        /// </summary>
        [Fact]
        public void PresetTest()
        {
            // TODO unit test for the property 'Preset'
        }

        /// <summary>
        /// Test the property 'Stamp'
        /// </summary>
        [Fact]
        public void StampTest()
        {
            // TODO unit test for the property 'Stamp'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'WidthMm'
        /// </summary>
        [Fact]
        public void WidthMmTest()
        {
            // TODO unit test for the property 'WidthMm'
        }

        /// <summary>
        /// Test the property 'Zpl'
        /// </summary>
        [Fact]
        public void ZplTest()
        {
            // TODO unit test for the property 'Zpl'
        }
    }
}
