/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// Barcode
    /// </summary>
    [DataContract(Name = "Barcode")]
    public partial class Barcode : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Barcode" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Barcode() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Barcode" /> class.
        /// </summary>
        /// <param name="blurMarginDots">Largest blur radius the symbol survives; 0 &#x3D; no margin (required).</param>
        /// <param name="checks">checks (required).</param>
        /// <param name="crossDpi">X-dimension at other print densities, same dot counts.</param>
        /// <param name="format">CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX (required).</param>
        /// <param name="moduleDots">Measured narrow-element width in printer dots (1D only).</param>
        /// <param name="quietLeftModules">quietLeftModules.</param>
        /// <param name="quietRightModules">quietRightModules.</param>
        /// <param name="value">value (required).</param>
        /// <param name="xDimensionMm">Physical narrow-element width at the analyzed density.</param>
        public Barcode(long blurMarginDots = default, List<Check> checks = default, List<DPIVerdict> crossDpi = default, string format = default, double moduleDots = default, double quietLeftModules = default, double quietRightModules = default, string value = default, double xDimensionMm = default)
        {
            this.BlurMarginDots = blurMarginDots;
            // to ensure "checks" is required (not null)
            if (checks == null)
            {
                throw new ArgumentNullException("checks is a required property for Barcode and cannot be null");
            }
            this.Checks = checks;
            // to ensure "format" is required (not null)
            if (format == null)
            {
                throw new ArgumentNullException("format is a required property for Barcode and cannot be null");
            }
            this.Format = format;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for Barcode and cannot be null");
            }
            this.Value = value;
            this.CrossDpi = crossDpi;
            this.ModuleDots = moduleDots;
            this.QuietLeftModules = quietLeftModules;
            this.QuietRightModules = quietRightModules;
            this.XDimensionMm = xDimensionMm;
        }

        /// <summary>
        /// Largest blur radius the symbol survives; 0 &#x3D; no margin
        /// </summary>
        /// <value>Largest blur radius the symbol survives; 0 &#x3D; no margin</value>
        [DataMember(Name = "blurMarginDots", IsRequired = true, EmitDefaultValue = true)]
        public long BlurMarginDots { get; set; }

        /// <summary>
        /// Gets or Sets Checks
        /// </summary>
        [DataMember(Name = "checks", IsRequired = true, EmitDefaultValue = true)]
        public List<Check> Checks { get; set; }

        /// <summary>
        /// X-dimension at other print densities, same dot counts
        /// </summary>
        /// <value>X-dimension at other print densities, same dot counts</value>
        [DataMember(Name = "crossDpi", EmitDefaultValue = true)]
        public List<DPIVerdict> CrossDpi { get; set; }

        /// <summary>
        /// CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX
        /// </summary>
        /// <value>CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX</value>
        [DataMember(Name = "format", IsRequired = true, EmitDefaultValue = true)]
        public string Format { get; set; }

        /// <summary>
        /// Measured narrow-element width in printer dots (1D only)
        /// </summary>
        /// <value>Measured narrow-element width in printer dots (1D only)</value>
        [DataMember(Name = "moduleDots", EmitDefaultValue = false)]
        public double ModuleDots { get; set; }

        /// <summary>
        /// Gets or Sets QuietLeftModules
        /// </summary>
        [DataMember(Name = "quietLeftModules", EmitDefaultValue = false)]
        public double QuietLeftModules { get; set; }

        /// <summary>
        /// Gets or Sets QuietRightModules
        /// </summary>
        [DataMember(Name = "quietRightModules", EmitDefaultValue = false)]
        public double QuietRightModules { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Physical narrow-element width at the analyzed density
        /// </summary>
        /// <value>Physical narrow-element width at the analyzed density</value>
        [DataMember(Name = "xDimensionMm", EmitDefaultValue = false)]
        public double XDimensionMm { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Barcode {\n");
            sb.Append("  BlurMarginDots: ").Append(BlurMarginDots).Append("\n");
            sb.Append("  Checks: ").Append(Checks).Append("\n");
            sb.Append("  CrossDpi: ").Append(CrossDpi).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  ModuleDots: ").Append(ModuleDots).Append("\n");
            sb.Append("  QuietLeftModules: ").Append(QuietLeftModules).Append("\n");
            sb.Append("  QuietRightModules: ").Append(QuietRightModules).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  XDimensionMm: ").Append(XDimensionMm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
