/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// ComposeOutputBody
    /// </summary>
    [DataContract(Name = "ComposeOutputBody")]
    public partial class ComposeOutputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComposeOutputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ComposeOutputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ComposeOutputBody" /> class.
        /// </summary>
        /// <param name="labels">Rendered previews when preview&#x3D;true.</param>
        /// <param name="warnings">warnings (required).</param>
        /// <param name="zpl">zpl (required).</param>
        public ComposeOutputBody(List<RenderedLabel> labels = default, List<string> warnings = default, string zpl = default)
        {
            // to ensure "warnings" is required (not null)
            if (warnings == null)
            {
                throw new ArgumentNullException("warnings is a required property for ComposeOutputBody and cannot be null");
            }
            this.Warnings = warnings;
            // to ensure "zpl" is required (not null)
            if (zpl == null)
            {
                throw new ArgumentNullException("zpl is a required property for ComposeOutputBody and cannot be null");
            }
            this.Zpl = zpl;
            this.Labels = labels;
        }

        /// <summary>
        /// Rendered previews when preview&#x3D;true
        /// </summary>
        /// <value>Rendered previews when preview&#x3D;true</value>
        [DataMember(Name = "labels", EmitDefaultValue = true)]
        public List<RenderedLabel> Labels { get; set; }

        /// <summary>
        /// Gets or Sets Warnings
        /// </summary>
        [DataMember(Name = "warnings", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Warnings { get; set; }

        /// <summary>
        /// Gets or Sets Zpl
        /// </summary>
        [DataMember(Name = "zpl", IsRequired = true, EmitDefaultValue = true)]
        public string Zpl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ComposeOutputBody {\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("  Zpl: ").Append(Zpl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
