/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// Element
    /// </summary>
    [DataContract(Name = "Element")]
    public partial class Element : IValidatableObject
    {
        /// <summary>
        /// Alignment when wrapping
        /// </summary>
        /// <value>Alignment when wrapping</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AlignEnum
        {
            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 1,

            /// <summary>
            /// Enum Left for value: left
            /// </summary>
            [EnumMember(Value = "left")]
            Left = 2,

            /// <summary>
            /// Enum Center for value: center
            /// </summary>
            [EnumMember(Value = "center")]
            Center = 3,

            /// <summary>
            /// Enum Right for value: right
            /// </summary>
            [EnumMember(Value = "right")]
            Right = 4,

            /// <summary>
            /// Enum Justify for value: justify
            /// </summary>
            [EnumMember(Value = "justify")]
            Justify = 5
        }


        /// <summary>
        /// Alignment when wrapping
        /// </summary>
        /// <value>Alignment when wrapping</value>
        [DataMember(Name = "align", EmitDefaultValue = false)]
        public AlignEnum? Align { get; set; }
        /// <summary>
        /// QR error correction (default M)
        /// </summary>
        /// <value>QR error correction (default M)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ErrorCorrectionEnum
        {
            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 1,

            /// <summary>
            /// Enum L for value: L
            /// </summary>
            [EnumMember(Value = "L")]
            L = 2,

            /// <summary>
            /// Enum M for value: M
            /// </summary>
            [EnumMember(Value = "M")]
            M = 3,

            /// <summary>
            /// Enum Q for value: Q
            /// </summary>
            [EnumMember(Value = "Q")]
            Q = 4,

            /// <summary>
            /// Enum H for value: H
            /// </summary>
            [EnumMember(Value = "H")]
            H = 5
        }


        /// <summary>
        /// QR error correction (default M)
        /// </summary>
        /// <value>QR error correction (default M)</value>
        [DataMember(Name = "errorCorrection", EmitDefaultValue = false)]
        public ErrorCorrectionEnum? ErrorCorrection { get; set; }
        /// <summary>
        /// Line direction
        /// </summary>
        /// <value>Line direction</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OrientationEnum
        {
            /// <summary>
            /// Enum Empty for value: 
            /// </summary>
            [EnumMember(Value = "")]
            Empty = 1,

            /// <summary>
            /// Enum H for value: h
            /// </summary>
            [EnumMember(Value = "h")]
            H = 2,

            /// <summary>
            /// Enum V for value: v
            /// </summary>
            [EnumMember(Value = "v")]
            V = 3
        }


        /// <summary>
        /// Line direction
        /// </summary>
        /// <value>Line direction</value>
        [DataMember(Name = "orientation", EmitDefaultValue = false)]
        public OrientationEnum? Orientation { get; set; }
        /// <summary>
        /// Defines Rotation
        /// </summary>
        public enum RotationEnum : long
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_90 for value: 90
            /// </summary>
            NUMBER_90 = 90,

            /// <summary>
            /// Enum NUMBER_180 for value: 180
            /// </summary>
            NUMBER_180 = 180,

            /// <summary>
            /// Enum NUMBER_270 for value: 270
            /// </summary>
            NUMBER_270 = 270
        }


        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>
        [DataMember(Name = "rotation", EmitDefaultValue = false)]
        public RotationEnum? Rotation { get; set; }
        /// <summary>
        /// What to place
        /// </summary>
        /// <value>What to place</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Text for value: text
            /// </summary>
            [EnumMember(Value = "text")]
            Text = 1,

            /// <summary>
            /// Enum Barcode128 for value: barcode128
            /// </summary>
            [EnumMember(Value = "barcode128")]
            Barcode128 = 2,

            /// <summary>
            /// Enum Barcode39 for value: barcode39
            /// </summary>
            [EnumMember(Value = "barcode39")]
            Barcode39 = 3,

            /// <summary>
            /// Enum Qr for value: qr
            /// </summary>
            [EnumMember(Value = "qr")]
            Qr = 4,

            /// <summary>
            /// Enum Datamatrix for value: datamatrix
            /// </summary>
            [EnumMember(Value = "datamatrix")]
            Datamatrix = 5,

            /// <summary>
            /// Enum Box for value: box
            /// </summary>
            [EnumMember(Value = "box")]
            Box = 6,

            /// <summary>
            /// Enum Line for value: line
            /// </summary>
            [EnumMember(Value = "line")]
            Line = 7,

            /// <summary>
            /// Enum Circle for value: circle
            /// </summary>
            [EnumMember(Value = "circle")]
            Circle = 8,

            /// <summary>
            /// Enum Image for value: image
            /// </summary>
            [EnumMember(Value = "image")]
            Image = 9,

            /// <summary>
            /// Enum Raw for value: raw
            /// </summary>
            [EnumMember(Value = "raw")]
            Raw = 10
        }


        /// <summary>
        /// What to place
        /// </summary>
        /// <value>What to place</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Element" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Element() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Element" /> class.
        /// </summary>
        /// <param name="align">Alignment when wrapping.</param>
        /// <param name="cornerRadius">Box corner rounding 0-8.</param>
        /// <param name="data">Barcode payload; {{name}} interpolates.</param>
        /// <param name="diameter">Circle diameter in dots.</param>
        /// <param name="errorCorrection">QR error correction (default M).</param>
        /// <param name="font">Printer font: 0 (scalable, default) or A-Z.</param>
        /// <param name="fontHeight">Character height in dots (text).</param>
        /// <param name="fontWidth">Character width in dots; 0 follows fontHeight.</param>
        /// <param name="height">Bar height in dots (1D) / box height in dots (box).</param>
        /// <param name="length">Line length in dots.</param>
        /// <param name="lines">Max lines when wrapping (default 1).</param>
        /// <param name="magnification">QR module magnification (default 3).</param>
        /// <param name="maxWidth">Wrap text into a block this many dots wide.</param>
        /// <param name="moduleSize">DataMatrix module size in dots (default 4).</param>
        /// <param name="moduleWidth">Narrow element width in dots (1D; default 3).</param>
        /// <param name="orientation">Line direction.</param>
        /// <param name="png">PNG/GIF/JPEG, base64-encoded.</param>
        /// <param name="printText">Print the human-readable line under 1D barcodes (default true).</param>
        /// <param name="rotation">rotation.</param>
        /// <param name="text">Text content; {{name}} interpolates from variables.</param>
        /// <param name="thickness">Stroke thickness in dots (default 1).</param>
        /// <param name="threshold">Bitonal threshold (default 128).</param>
        /// <param name="type">What to place (required).</param>
        /// <param name="width">Box/image width in dots.</param>
        /// <param name="x">Left edge in dots.</param>
        /// <param name="y">Top edge in dots.</param>
        /// <param name="zpl">Verbatim ZPL commands (raw only) - the escape hatch.</param>
        public Element(AlignEnum? align = default, long cornerRadius = default, string data = default, long diameter = default, ErrorCorrectionEnum? errorCorrection = default, string font = default, long fontHeight = default, long fontWidth = default, long height = default, long length = default, long lines = default, long magnification = default, long maxWidth = default, long moduleSize = default, long moduleWidth = default, OrientationEnum? orientation = default, string png = default, bool printText = default, RotationEnum? rotation = default, string text = default, long thickness = default, long threshold = default, TypeEnum type = default, long width = default, long x = default, long y = default, string zpl = default)
        {
            this.Type = type;
            this.Align = align;
            this.CornerRadius = cornerRadius;
            this.Data = data;
            this.Diameter = diameter;
            this.ErrorCorrection = errorCorrection;
            this.Font = font;
            this.FontHeight = fontHeight;
            this.FontWidth = fontWidth;
            this.Height = height;
            this.Length = length;
            this.Lines = lines;
            this.Magnification = magnification;
            this.MaxWidth = maxWidth;
            this.ModuleSize = moduleSize;
            this.ModuleWidth = moduleWidth;
            this.Orientation = orientation;
            this.Png = png;
            this.PrintText = printText;
            this.Rotation = rotation;
            this.Text = text;
            this.Thickness = thickness;
            this.Threshold = threshold;
            this.Width = width;
            this.X = x;
            this.Y = y;
            this.Zpl = zpl;
        }

        /// <summary>
        /// Box corner rounding 0-8
        /// </summary>
        /// <value>Box corner rounding 0-8</value>
        [DataMember(Name = "cornerRadius", EmitDefaultValue = false)]
        public long CornerRadius { get; set; }

        /// <summary>
        /// Barcode payload; {{name}} interpolates
        /// </summary>
        /// <value>Barcode payload; {{name}} interpolates</value>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public string Data { get; set; }

        /// <summary>
        /// Circle diameter in dots
        /// </summary>
        /// <value>Circle diameter in dots</value>
        [DataMember(Name = "diameter", EmitDefaultValue = false)]
        public long Diameter { get; set; }

        /// <summary>
        /// Printer font: 0 (scalable, default) or A-Z
        /// </summary>
        /// <value>Printer font: 0 (scalable, default) or A-Z</value>
        [DataMember(Name = "font", EmitDefaultValue = false)]
        public string Font { get; set; }

        /// <summary>
        /// Character height in dots (text)
        /// </summary>
        /// <value>Character height in dots (text)</value>
        [DataMember(Name = "fontHeight", EmitDefaultValue = false)]
        public long FontHeight { get; set; }

        /// <summary>
        /// Character width in dots; 0 follows fontHeight
        /// </summary>
        /// <value>Character width in dots; 0 follows fontHeight</value>
        [DataMember(Name = "fontWidth", EmitDefaultValue = false)]
        public long FontWidth { get; set; }

        /// <summary>
        /// Bar height in dots (1D) / box height in dots (box)
        /// </summary>
        /// <value>Bar height in dots (1D) / box height in dots (box)</value>
        [DataMember(Name = "height", EmitDefaultValue = false)]
        public long Height { get; set; }

        /// <summary>
        /// Line length in dots
        /// </summary>
        /// <value>Line length in dots</value>
        [DataMember(Name = "length", EmitDefaultValue = false)]
        public long Length { get; set; }

        /// <summary>
        /// Max lines when wrapping (default 1)
        /// </summary>
        /// <value>Max lines when wrapping (default 1)</value>
        [DataMember(Name = "lines", EmitDefaultValue = false)]
        public long Lines { get; set; }

        /// <summary>
        /// QR module magnification (default 3)
        /// </summary>
        /// <value>QR module magnification (default 3)</value>
        [DataMember(Name = "magnification", EmitDefaultValue = false)]
        public long Magnification { get; set; }

        /// <summary>
        /// Wrap text into a block this many dots wide
        /// </summary>
        /// <value>Wrap text into a block this many dots wide</value>
        [DataMember(Name = "maxWidth", EmitDefaultValue = false)]
        public long MaxWidth { get; set; }

        /// <summary>
        /// DataMatrix module size in dots (default 4)
        /// </summary>
        /// <value>DataMatrix module size in dots (default 4)</value>
        [DataMember(Name = "moduleSize", EmitDefaultValue = false)]
        public long ModuleSize { get; set; }

        /// <summary>
        /// Narrow element width in dots (1D; default 3)
        /// </summary>
        /// <value>Narrow element width in dots (1D; default 3)</value>
        [DataMember(Name = "moduleWidth", EmitDefaultValue = false)]
        public long ModuleWidth { get; set; }

        /// <summary>
        /// PNG/GIF/JPEG, base64-encoded
        /// </summary>
        /// <value>PNG/GIF/JPEG, base64-encoded</value>
        [DataMember(Name = "png", EmitDefaultValue = false)]
        public string Png { get; set; }

        /// <summary>
        /// Print the human-readable line under 1D barcodes (default true)
        /// </summary>
        /// <value>Print the human-readable line under 1D barcodes (default true)</value>
        [DataMember(Name = "printText", EmitDefaultValue = true)]
        public bool PrintText { get; set; }

        /// <summary>
        /// Text content; {{name}} interpolates from variables
        /// </summary>
        /// <value>Text content; {{name}} interpolates from variables</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Stroke thickness in dots (default 1)
        /// </summary>
        /// <value>Stroke thickness in dots (default 1)</value>
        [DataMember(Name = "thickness", EmitDefaultValue = false)]
        public long Thickness { get; set; }

        /// <summary>
        /// Bitonal threshold (default 128)
        /// </summary>
        /// <value>Bitonal threshold (default 128)</value>
        [DataMember(Name = "threshold", EmitDefaultValue = false)]
        public long Threshold { get; set; }

        /// <summary>
        /// Box/image width in dots
        /// </summary>
        /// <value>Box/image width in dots</value>
        [DataMember(Name = "width", EmitDefaultValue = false)]
        public long Width { get; set; }

        /// <summary>
        /// Left edge in dots
        /// </summary>
        /// <value>Left edge in dots</value>
        [DataMember(Name = "x", EmitDefaultValue = false)]
        public long X { get; set; }

        /// <summary>
        /// Top edge in dots
        /// </summary>
        /// <value>Top edge in dots</value>
        [DataMember(Name = "y", EmitDefaultValue = false)]
        public long Y { get; set; }

        /// <summary>
        /// Verbatim ZPL commands (raw only) - the escape hatch
        /// </summary>
        /// <value>Verbatim ZPL commands (raw only) - the escape hatch</value>
        [DataMember(Name = "zpl", EmitDefaultValue = false)]
        public string Zpl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Element {\n");
            sb.Append("  Align: ").Append(Align).Append("\n");
            sb.Append("  CornerRadius: ").Append(CornerRadius).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Diameter: ").Append(Diameter).Append("\n");
            sb.Append("  ErrorCorrection: ").Append(ErrorCorrection).Append("\n");
            sb.Append("  Font: ").Append(Font).Append("\n");
            sb.Append("  FontHeight: ").Append(FontHeight).Append("\n");
            sb.Append("  FontWidth: ").Append(FontWidth).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Lines: ").Append(Lines).Append("\n");
            sb.Append("  Magnification: ").Append(Magnification).Append("\n");
            sb.Append("  MaxWidth: ").Append(MaxWidth).Append("\n");
            sb.Append("  ModuleSize: ").Append(ModuleSize).Append("\n");
            sb.Append("  ModuleWidth: ").Append(ModuleWidth).Append("\n");
            sb.Append("  Orientation: ").Append(Orientation).Append("\n");
            sb.Append("  Png: ").Append(Png).Append("\n");
            sb.Append("  PrintText: ").Append(PrintText).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Thickness: ").Append(Thickness).Append("\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Zpl: ").Append(Zpl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CornerRadius (long) maximum
            if (this.CornerRadius > (long)8)
            {
                yield return new ValidationResult("Invalid value for CornerRadius, must be a value less than or equal to 8.", new [] { "CornerRadius" });
            }

            // CornerRadius (long) minimum
            if (this.CornerRadius < (long)0)
            {
                yield return new ValidationResult("Invalid value for CornerRadius, must be a value greater than or equal to 0.", new [] { "CornerRadius" });
            }

            // Threshold (long) maximum
            if (this.Threshold > (long)255)
            {
                yield return new ValidationResult("Invalid value for Threshold, must be a value less than or equal to 255.", new [] { "Threshold" });
            }

            // Threshold (long) minimum
            if (this.Threshold < (long)0)
            {
                yield return new ValidationResult("Invalid value for Threshold, must be a value greater than or equal to 0.", new [] { "Threshold" });
            }

            // X (long) minimum
            if (this.X < (long)0)
            {
                yield return new ValidationResult("Invalid value for X, must be a value greater than or equal to 0.", new [] { "X" });
            }

            // Y (long) minimum
            if (this.Y < (long)0)
            {
                yield return new ValidationResult("Invalid value for Y, must be a value greater than or equal to 0.", new [] { "Y" });
            }

            yield break;
        }
    }

}
