/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// HeldJob
    /// </summary>
    [DataContract(Name = "HeldJob")]
    public partial class HeldJob : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HeldJob" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HeldJob() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HeldJob" /> class.
        /// </summary>
        /// <param name="bytes">Size of the held frame (required).</param>
        /// <param name="receivedAt">receivedAt (required).</param>
        /// <param name="source">How it arrived: tcp or https (required).</param>
        public HeldJob(long bytes = default, DateTime receivedAt = default, string source = default)
        {
            this.Bytes = bytes;
            this.ReceivedAt = receivedAt;
            // to ensure "source" is required (not null)
            if (source == null)
            {
                throw new ArgumentNullException("source is a required property for HeldJob and cannot be null");
            }
            this.Source = source;
        }

        /// <summary>
        /// Size of the held frame
        /// </summary>
        /// <value>Size of the held frame</value>
        [DataMember(Name = "bytes", IsRequired = true, EmitDefaultValue = true)]
        public long Bytes { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedAt
        /// </summary>
        [DataMember(Name = "receivedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ReceivedAt { get; set; }

        /// <summary>
        /// How it arrived: tcp or https
        /// </summary>
        /// <value>How it arrived: tcp or https</value>
        [DataMember(Name = "source", IsRequired = true, EmitDefaultValue = true)]
        public string Source { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HeldJob {\n");
            sb.Append("  Bytes: ").Append(Bytes).Append("\n");
            sb.Append("  ReceivedAt: ").Append(ReceivedAt).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
