/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// HostStatus
    /// </summary>
    [DataContract(Name = "HostStatus")]
    public partial class HostStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HostStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostStatus" /> class.
        /// </summary>
        /// <param name="blocking">True when any condition stops printing (required).</param>
        /// <param name="bufferFull">bufferFull (required).</param>
        /// <param name="commSettings">Raw communication-settings code (required).</param>
        /// <param name="corruptRam">corruptRam (required).</param>
        /// <param name="diagnosticMode">diagnosticMode (required).</param>
        /// <param name="formatsInBuffer">Jobs waiting in the receive buffer (required).</param>
        /// <param name="functionSettings">Raw function-settings code (required).</param>
        /// <param name="graphicsStored">graphicsStored (required).</param>
        /// <param name="headUp">headUp (required).</param>
        /// <param name="labelLengthDots">labelLengthDots (required).</param>
        /// <param name="labelsRemaining">labelsRemaining (required).</param>
        /// <param name="overTemp">overTemp (required).</param>
        /// <param name="paperOut">paperOut (required).</param>
        /// <param name="partialFormat">partialFormat (required).</param>
        /// <param name="password">password (required).</param>
        /// <param name="paused">paused (required).</param>
        /// <param name="printMode">rewind, peel-off, tear-off, cutter or applicator (required).</param>
        /// <param name="ribbonOut">ribbonOut (required).</param>
        /// <param name="staticRam">staticRam (required).</param>
        /// <param name="thermalTransfer">thermalTransfer (required).</param>
        /// <param name="underTemp">underTemp (required).</param>
        public HostStatus(bool blocking = default, bool bufferFull = default, string commSettings = default, bool corruptRam = default, bool diagnosticMode = default, long formatsInBuffer = default, string functionSettings = default, long graphicsStored = default, bool headUp = default, long labelLengthDots = default, long labelsRemaining = default, bool overTemp = default, bool paperOut = default, bool partialFormat = default, string password = default, bool paused = default, string printMode = default, bool ribbonOut = default, bool staticRam = default, bool thermalTransfer = default, bool underTemp = default)
        {
            this.Blocking = blocking;
            this.BufferFull = bufferFull;
            // to ensure "commSettings" is required (not null)
            if (commSettings == null)
            {
                throw new ArgumentNullException("commSettings is a required property for HostStatus and cannot be null");
            }
            this.CommSettings = commSettings;
            this.CorruptRam = corruptRam;
            this.DiagnosticMode = diagnosticMode;
            this.FormatsInBuffer = formatsInBuffer;
            // to ensure "functionSettings" is required (not null)
            if (functionSettings == null)
            {
                throw new ArgumentNullException("functionSettings is a required property for HostStatus and cannot be null");
            }
            this.FunctionSettings = functionSettings;
            this.GraphicsStored = graphicsStored;
            this.HeadUp = headUp;
            this.LabelLengthDots = labelLengthDots;
            this.LabelsRemaining = labelsRemaining;
            this.OverTemp = overTemp;
            this.PaperOut = paperOut;
            this.PartialFormat = partialFormat;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for HostStatus and cannot be null");
            }
            this.Password = password;
            this.Paused = paused;
            // to ensure "printMode" is required (not null)
            if (printMode == null)
            {
                throw new ArgumentNullException("printMode is a required property for HostStatus and cannot be null");
            }
            this.PrintMode = printMode;
            this.RibbonOut = ribbonOut;
            this.StaticRam = staticRam;
            this.ThermalTransfer = thermalTransfer;
            this.UnderTemp = underTemp;
        }

        /// <summary>
        /// True when any condition stops printing
        /// </summary>
        /// <value>True when any condition stops printing</value>
        [DataMember(Name = "blocking", IsRequired = true, EmitDefaultValue = true)]
        public bool Blocking { get; set; }

        /// <summary>
        /// Gets or Sets BufferFull
        /// </summary>
        [DataMember(Name = "bufferFull", IsRequired = true, EmitDefaultValue = true)]
        public bool BufferFull { get; set; }

        /// <summary>
        /// Raw communication-settings code
        /// </summary>
        /// <value>Raw communication-settings code</value>
        [DataMember(Name = "commSettings", IsRequired = true, EmitDefaultValue = true)]
        public string CommSettings { get; set; }

        /// <summary>
        /// Gets or Sets CorruptRam
        /// </summary>
        [DataMember(Name = "corruptRam", IsRequired = true, EmitDefaultValue = true)]
        public bool CorruptRam { get; set; }

        /// <summary>
        /// Gets or Sets DiagnosticMode
        /// </summary>
        [DataMember(Name = "diagnosticMode", IsRequired = true, EmitDefaultValue = true)]
        public bool DiagnosticMode { get; set; }

        /// <summary>
        /// Jobs waiting in the receive buffer
        /// </summary>
        /// <value>Jobs waiting in the receive buffer</value>
        [DataMember(Name = "formatsInBuffer", IsRequired = true, EmitDefaultValue = true)]
        public long FormatsInBuffer { get; set; }

        /// <summary>
        /// Raw function-settings code
        /// </summary>
        /// <value>Raw function-settings code</value>
        [DataMember(Name = "functionSettings", IsRequired = true, EmitDefaultValue = true)]
        public string FunctionSettings { get; set; }

        /// <summary>
        /// Gets or Sets GraphicsStored
        /// </summary>
        [DataMember(Name = "graphicsStored", IsRequired = true, EmitDefaultValue = true)]
        public long GraphicsStored { get; set; }

        /// <summary>
        /// Gets or Sets HeadUp
        /// </summary>
        [DataMember(Name = "headUp", IsRequired = true, EmitDefaultValue = true)]
        public bool HeadUp { get; set; }

        /// <summary>
        /// Gets or Sets LabelLengthDots
        /// </summary>
        [DataMember(Name = "labelLengthDots", IsRequired = true, EmitDefaultValue = true)]
        public long LabelLengthDots { get; set; }

        /// <summary>
        /// Gets or Sets LabelsRemaining
        /// </summary>
        [DataMember(Name = "labelsRemaining", IsRequired = true, EmitDefaultValue = true)]
        public long LabelsRemaining { get; set; }

        /// <summary>
        /// Gets or Sets OverTemp
        /// </summary>
        [DataMember(Name = "overTemp", IsRequired = true, EmitDefaultValue = true)]
        public bool OverTemp { get; set; }

        /// <summary>
        /// Gets or Sets PaperOut
        /// </summary>
        [DataMember(Name = "paperOut", IsRequired = true, EmitDefaultValue = true)]
        public bool PaperOut { get; set; }

        /// <summary>
        /// Gets or Sets PartialFormat
        /// </summary>
        [DataMember(Name = "partialFormat", IsRequired = true, EmitDefaultValue = true)]
        public bool PartialFormat { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets Paused
        /// </summary>
        [DataMember(Name = "paused", IsRequired = true, EmitDefaultValue = true)]
        public bool Paused { get; set; }

        /// <summary>
        /// rewind, peel-off, tear-off, cutter or applicator
        /// </summary>
        /// <value>rewind, peel-off, tear-off, cutter or applicator</value>
        [DataMember(Name = "printMode", IsRequired = true, EmitDefaultValue = true)]
        public string PrintMode { get; set; }

        /// <summary>
        /// Gets or Sets RibbonOut
        /// </summary>
        [DataMember(Name = "ribbonOut", IsRequired = true, EmitDefaultValue = true)]
        public bool RibbonOut { get; set; }

        /// <summary>
        /// Gets or Sets StaticRam
        /// </summary>
        [DataMember(Name = "staticRam", IsRequired = true, EmitDefaultValue = true)]
        public bool StaticRam { get; set; }

        /// <summary>
        /// Gets or Sets ThermalTransfer
        /// </summary>
        [DataMember(Name = "thermalTransfer", IsRequired = true, EmitDefaultValue = true)]
        public bool ThermalTransfer { get; set; }

        /// <summary>
        /// Gets or Sets UnderTemp
        /// </summary>
        [DataMember(Name = "underTemp", IsRequired = true, EmitDefaultValue = true)]
        public bool UnderTemp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HostStatus {\n");
            sb.Append("  Blocking: ").Append(Blocking).Append("\n");
            sb.Append("  BufferFull: ").Append(BufferFull).Append("\n");
            sb.Append("  CommSettings: ").Append(CommSettings).Append("\n");
            sb.Append("  CorruptRam: ").Append(CorruptRam).Append("\n");
            sb.Append("  DiagnosticMode: ").Append(DiagnosticMode).Append("\n");
            sb.Append("  FormatsInBuffer: ").Append(FormatsInBuffer).Append("\n");
            sb.Append("  FunctionSettings: ").Append(FunctionSettings).Append("\n");
            sb.Append("  GraphicsStored: ").Append(GraphicsStored).Append("\n");
            sb.Append("  HeadUp: ").Append(HeadUp).Append("\n");
            sb.Append("  LabelLengthDots: ").Append(LabelLengthDots).Append("\n");
            sb.Append("  LabelsRemaining: ").Append(LabelsRemaining).Append("\n");
            sb.Append("  OverTemp: ").Append(OverTemp).Append("\n");
            sb.Append("  PaperOut: ").Append(PaperOut).Append("\n");
            sb.Append("  PartialFormat: ").Append(PartialFormat).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Paused: ").Append(Paused).Append("\n");
            sb.Append("  PrintMode: ").Append(PrintMode).Append("\n");
            sb.Append("  RibbonOut: ").Append(RibbonOut).Append("\n");
            sb.Append("  StaticRam: ").Append(StaticRam).Append("\n");
            sb.Append("  ThermalTransfer: ").Append(ThermalTransfer).Append("\n");
            sb.Append("  UnderTemp: ").Append(UnderTemp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
