/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// HostStatusOutputBody
    /// </summary>
    [DataContract(Name = "HostStatusOutputBody")]
    public partial class HostStatusOutputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HostStatusOutputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HostStatusOutputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HostStatusOutputBody" /> class.
        /// </summary>
        /// <param name="fields">Every field with its documented meaning and raw token (required).</param>
        /// <param name="status">status (required).</param>
        public HostStatusOutputBody(List<StatusField> fields = default, HostStatus status = default)
        {
            // to ensure "fields" is required (not null)
            if (fields == null)
            {
                throw new ArgumentNullException("fields is a required property for HostStatusOutputBody and cannot be null");
            }
            this.Fields = fields;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for HostStatusOutputBody and cannot be null");
            }
            this.Status = status;
        }

        /// <summary>
        /// Every field with its documented meaning and raw token
        /// </summary>
        /// <value>Every field with its documented meaning and raw token</value>
        [DataMember(Name = "fields", IsRequired = true, EmitDefaultValue = true)]
        public List<StatusField> Fields { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public HostStatus Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HostStatusOutputBody {\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
