/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// HtmlInputBody
    /// </summary>
    [DataContract(Name = "HtmlInputBody")]
    public partial class HtmlInputBody : IValidatableObject
    {
        /// <summary>
        /// Defines Compression
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CompressionEnum
        {
            /// <summary>
            /// Enum Acs for value: acs
            /// </summary>
            [EnumMember(Value = "acs")]
            Acs = 1,

            /// <summary>
            /// Enum Z64 for value: z64
            /// </summary>
            [EnumMember(Value = "z64")]
            Z64 = 2
        }


        /// <summary>
        /// Gets or Sets Compression
        /// </summary>
        [DataMember(Name = "compression", EmitDefaultValue = false)]
        public CompressionEnum? Compression { get; set; }
        /// <summary>
        /// Defines Dpmm
        /// </summary>
        public enum DpmmEnum : long
        {
            /// <summary>
            /// Enum NUMBER_6 for value: 6
            /// </summary>
            NUMBER_6 = 6,

            /// <summary>
            /// Enum NUMBER_8 for value: 8
            /// </summary>
            NUMBER_8 = 8,

            /// <summary>
            /// Enum NUMBER_12 for value: 12
            /// </summary>
            NUMBER_12 = 12,

            /// <summary>
            /// Enum NUMBER_24 for value: 24
            /// </summary>
            NUMBER_24 = 24
        }


        /// <summary>
        /// Gets or Sets Dpmm
        /// </summary>
        [DataMember(Name = "dpmm", EmitDefaultValue = false)]
        public DpmmEnum? Dpmm { get; set; }
        /// <summary>
        /// Defines Preset
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PresetEnum
        {
            /// <summary>
            /// Enum _4x6 for value: 4x6
            /// </summary>
            [EnumMember(Value = "4x6")]
            _4x6 = 1,

            /// <summary>
            /// Enum _6x4 for value: 6x4
            /// </summary>
            [EnumMember(Value = "6x4")]
            _6x4 = 2,

            /// <summary>
            /// Enum _4x4 for value: 4x4
            /// </summary>
            [EnumMember(Value = "4x4")]
            _4x4 = 3,

            /// <summary>
            /// Enum _4x2 for value: 4x2
            /// </summary>
            [EnumMember(Value = "4x2")]
            _4x2 = 4,

            /// <summary>
            /// Enum _2x4 for value: 2x4
            /// </summary>
            [EnumMember(Value = "2x4")]
            _2x4 = 5,

            /// <summary>
            /// Enum _3x5 for value: 3x5
            /// </summary>
            [EnumMember(Value = "3x5")]
            _3x5 = 6,

            /// <summary>
            /// Enum _5x3 for value: 5x3
            /// </summary>
            [EnumMember(Value = "5x3")]
            _5x3 = 7,

            /// <summary>
            /// Enum _2x3 for value: 2x3
            /// </summary>
            [EnumMember(Value = "2x3")]
            _2x3 = 8,

            /// <summary>
            /// Enum _3x2 for value: 3x2
            /// </summary>
            [EnumMember(Value = "3x2")]
            _3x2 = 9,

            /// <summary>
            /// Enum Netstamp for value: netstamp
            /// </summary>
            [EnumMember(Value = "netstamp")]
            Netstamp = 10,

            /// <summary>
            /// Enum _225x125 for value: 2.25x1.25
            /// </summary>
            [EnumMember(Value = "2.25x1.25")]
            _225x125 = 11,

            /// <summary>
            /// Enum _2x1 for value: 2x1
            /// </summary>
            [EnumMember(Value = "2x1")]
            _2x1 = 12,

            /// <summary>
            /// Enum _3x1 for value: 3x1
            /// </summary>
            [EnumMember(Value = "3x1")]
            _3x1 = 13,

            /// <summary>
            /// Enum _4x1 for value: 4x1
            /// </summary>
            [EnumMember(Value = "4x1")]
            _4x1 = 14,

            /// <summary>
            /// Enum _1x1 for value: 1x1
            /// </summary>
            [EnumMember(Value = "1x1")]
            _1x1 = 15,

            /// <summary>
            /// Enum _4x3 for value: 4x3
            /// </summary>
            [EnumMember(Value = "4x3")]
            _4x3 = 16,

            /// <summary>
            /// Enum _4x8 for value: 4x8
            /// </summary>
            [EnumMember(Value = "4x8")]
            _4x8 = 17,

            /// <summary>
            /// Enum A6 for value: a6
            /// </summary>
            [EnumMember(Value = "a6")]
            A6 = 18
        }


        /// <summary>
        /// Gets or Sets Preset
        /// </summary>
        [DataMember(Name = "preset", EmitDefaultValue = false)]
        public PresetEnum? Preset { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlInputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HtmlInputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HtmlInputBody" /> class.
        /// </summary>
        /// <param name="compression">compression.</param>
        /// <param name="dpmm">dpmm.</param>
        /// <param name="heightMm">heightMm.</param>
        /// <param name="html">Label markup: HTML/CSS plus &lt;zpl-barcode&gt; elements (required).</param>
        /// <param name="preset">preset.</param>
        /// <param name="threshold">threshold.</param>
        /// <param name="widthMm">widthMm.</param>
        public HtmlInputBody(CompressionEnum? compression = default, DpmmEnum? dpmm = default, double heightMm = default, string html = default, PresetEnum? preset = default, long threshold = default, double widthMm = default)
        {
            // to ensure "html" is required (not null)
            if (html == null)
            {
                throw new ArgumentNullException("html is a required property for HtmlInputBody and cannot be null");
            }
            this.Html = html;
            this.Compression = compression;
            this.Dpmm = dpmm;
            this.HeightMm = heightMm;
            this.Preset = preset;
            this.Threshold = threshold;
            this.WidthMm = widthMm;
        }

        /// <summary>
        /// Gets or Sets HeightMm
        /// </summary>
        [DataMember(Name = "heightMm", EmitDefaultValue = false)]
        public double HeightMm { get; set; }

        /// <summary>
        /// Label markup: HTML/CSS plus &lt;zpl-barcode&gt; elements
        /// </summary>
        /// <value>Label markup: HTML/CSS plus &lt;zpl-barcode&gt; elements</value>
        [DataMember(Name = "html", IsRequired = true, EmitDefaultValue = true)]
        public string Html { get; set; }

        /// <summary>
        /// Gets or Sets Threshold
        /// </summary>
        [DataMember(Name = "threshold", EmitDefaultValue = false)]
        public long Threshold { get; set; }

        /// <summary>
        /// Gets or Sets WidthMm
        /// </summary>
        [DataMember(Name = "widthMm", EmitDefaultValue = false)]
        public double WidthMm { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HtmlInputBody {\n");
            sb.Append("  Compression: ").Append(Compression).Append("\n");
            sb.Append("  Dpmm: ").Append(Dpmm).Append("\n");
            sb.Append("  HeightMm: ").Append(HeightMm).Append("\n");
            sb.Append("  Html: ").Append(Html).Append("\n");
            sb.Append("  Preset: ").Append(Preset).Append("\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("  WidthMm: ").Append(WidthMm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // HeightMm (double) minimum
            if (this.HeightMm < (double)0)
            {
                yield return new ValidationResult("Invalid value for HeightMm, must be a value greater than or equal to 0.", new [] { "HeightMm" });
            }

            // Threshold (long) maximum
            if (this.Threshold > (long)255)
            {
                yield return new ValidationResult("Invalid value for Threshold, must be a value less than or equal to 255.", new [] { "Threshold" });
            }

            // Threshold (long) minimum
            if (this.Threshold < (long)1)
            {
                yield return new ValidationResult("Invalid value for Threshold, must be a value greater than or equal to 1.", new [] { "Threshold" });
            }

            // WidthMm (double) minimum
            if (this.WidthMm < (double)0)
            {
                yield return new ValidationResult("Invalid value for WidthMm, must be a value greater than or equal to 0.", new [] { "WidthMm" });
            }

            yield break;
        }
    }

}
