/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// JobOutputBody
    /// </summary>
    [DataContract(Name = "JobOutputBody")]
    public partial class JobOutputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobOutputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JobOutputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobOutputBody" /> class.
        /// </summary>
        /// <param name="labels">URLs of the rendered label PNGs (required).</param>
        /// <param name="zpl">The raw ZPL as received (required).</param>
        public JobOutputBody(List<string> labels = default, string zpl = default)
        {
            // to ensure "labels" is required (not null)
            if (labels == null)
            {
                throw new ArgumentNullException("labels is a required property for JobOutputBody and cannot be null");
            }
            this.Labels = labels;
            // to ensure "zpl" is required (not null)
            if (zpl == null)
            {
                throw new ArgumentNullException("zpl is a required property for JobOutputBody and cannot be null");
            }
            this.Zpl = zpl;
        }

        /// <summary>
        /// URLs of the rendered label PNGs
        /// </summary>
        /// <value>URLs of the rendered label PNGs</value>
        [DataMember(Name = "labels", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Labels { get; set; }

        /// <summary>
        /// The raw ZPL as received
        /// </summary>
        /// <value>The raw ZPL as received</value>
        [DataMember(Name = "zpl", IsRequired = true, EmitDefaultValue = true)]
        public string Zpl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobOutputBody {\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Zpl: ").Append(Zpl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
