/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// JobSummary
    /// </summary>
    [DataContract(Name = "JobSummary")]
    public partial class JobSummary : IValidatableObject
    {
        /// <summary>
        /// Defines Source
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SourceEnum
        {
            /// <summary>
            /// Enum Tcp for value: tcp
            /// </summary>
            [EnumMember(Value = "tcp")]
            Tcp = 1,

            /// <summary>
            /// Enum Https for value: https
            /// </summary>
            [EnumMember(Value = "https")]
            Https = 2
        }


        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name = "source", IsRequired = true, EmitDefaultValue = true)]
        public SourceEnum Source { get; set; }
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Rendered for value: rendered
            /// </summary>
            [EnumMember(Value = "rendered")]
            Rendered = 1,

            /// <summary>
            /// Enum RenderFailed for value: render_failed
            /// </summary>
            [EnumMember(Value = "render_failed")]
            RenderFailed = 2
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JobSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JobSummary" /> class.
        /// </summary>
        /// <param name="error">error.</param>
        /// <param name="id">id (required).</param>
        /// <param name="labelCount">labelCount (required).</param>
        /// <param name="receivedAt">receivedAt (required).</param>
        /// <param name="source">source (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="zplBytes">zplBytes (required).</param>
        public JobSummary(string error = default, long id = default, long labelCount = default, DateTime receivedAt = default, SourceEnum source = default, StatusEnum status = default, long zplBytes = default)
        {
            this.Id = id;
            this.LabelCount = labelCount;
            this.ReceivedAt = receivedAt;
            this.Source = source;
            this.Status = status;
            this.ZplBytes = zplBytes;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets LabelCount
        /// </summary>
        [DataMember(Name = "labelCount", IsRequired = true, EmitDefaultValue = true)]
        public long LabelCount { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedAt
        /// </summary>
        [DataMember(Name = "receivedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ReceivedAt { get; set; }

        /// <summary>
        /// Gets or Sets ZplBytes
        /// </summary>
        [DataMember(Name = "zplBytes", IsRequired = true, EmitDefaultValue = true)]
        public long ZplBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobSummary {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LabelCount: ").Append(LabelCount).Append("\n");
            sb.Append("  ReceivedAt: ").Append(ReceivedAt).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ZplBytes: ").Append(ZplBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
