/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// ListJobsOutputBody
    /// </summary>
    [DataContract(Name = "ListJobsOutputBody")]
    public partial class ListJobsOutputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListJobsOutputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListJobsOutputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListJobsOutputBody" /> class.
        /// </summary>
        /// <param name="jobs">jobs (required).</param>
        public ListJobsOutputBody(List<JobSummary> jobs = default)
        {
            // to ensure "jobs" is required (not null)
            if (jobs == null)
            {
                throw new ArgumentNullException("jobs is a required property for ListJobsOutputBody and cannot be null");
            }
            this.Jobs = jobs;
        }

        /// <summary>
        /// Gets or Sets Jobs
        /// </summary>
        [DataMember(Name = "jobs", IsRequired = true, EmitDefaultValue = true)]
        public List<JobSummary> Jobs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListJobsOutputBody {\n");
            sb.Append("  Jobs: ").Append(Jobs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
