/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// MediaInputBody
    /// </summary>
    [DataContract(Name = "MediaInputBody")]
    public partial class MediaInputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaInputBody" /> class.
        /// </summary>
        /// <param name="labels">Labels on the roll; 0 for an endless roll.</param>
        /// <param name="ribbonMetres">Ribbon on the spool in metres; 0 for endless, which is also what direct thermal looks like.</param>
        public MediaInputBody(long labels = default, double ribbonMetres = default)
        {
            this.Labels = labels;
            this.RibbonMetres = ribbonMetres;
        }

        /// <summary>
        /// Labels on the roll; 0 for an endless roll
        /// </summary>
        /// <value>Labels on the roll; 0 for an endless roll</value>
        [DataMember(Name = "labels", EmitDefaultValue = false)]
        public long Labels { get; set; }

        /// <summary>
        /// Ribbon on the spool in metres; 0 for endless, which is also what direct thermal looks like
        /// </summary>
        /// <value>Ribbon on the spool in metres; 0 for endless, which is also what direct thermal looks like</value>
        [DataMember(Name = "ribbonMetres", EmitDefaultValue = false)]
        public double RibbonMetres { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MediaInputBody {\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  RibbonMetres: ").Append(RibbonMetres).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Labels (long) maximum
            if (this.Labels > (long)1000000)
            {
                yield return new ValidationResult("Invalid value for Labels, must be a value less than or equal to 1000000.", new [] { "Labels" });
            }

            // Labels (long) minimum
            if (this.Labels < (long)0)
            {
                yield return new ValidationResult("Invalid value for Labels, must be a value greater than or equal to 0.", new [] { "Labels" });
            }

            // RibbonMetres (double) maximum
            if (this.RibbonMetres > (double)10000)
            {
                yield return new ValidationResult("Invalid value for RibbonMetres, must be a value less than or equal to 10000.", new [] { "RibbonMetres" });
            }

            // RibbonMetres (double) minimum
            if (this.RibbonMetres < (double)0)
            {
                yield return new ValidationResult("Invalid value for RibbonMetres, must be a value greater than or equal to 0.", new [] { "RibbonMetres" });
            }

            yield break;
        }
    }

}
