/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// PreflightOutputBody
    /// </summary>
    [DataContract(Name = "PreflightOutputBody")]
    public partial class PreflightOutputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreflightOutputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PreflightOutputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PreflightOutputBody" /> class.
        /// </summary>
        /// <param name="labels">One report per rendered label (required).</param>
        /// <param name="lint">Static ZPL findings: structure, encoding, bounds (required).</param>
        public PreflightOutputBody(List<Report> labels = default, List<Finding> lint = default)
        {
            // to ensure "labels" is required (not null)
            if (labels == null)
            {
                throw new ArgumentNullException("labels is a required property for PreflightOutputBody and cannot be null");
            }
            this.Labels = labels;
            // to ensure "lint" is required (not null)
            if (lint == null)
            {
                throw new ArgumentNullException("lint is a required property for PreflightOutputBody and cannot be null");
            }
            this.Lint = lint;
        }

        /// <summary>
        /// One report per rendered label
        /// </summary>
        /// <value>One report per rendered label</value>
        [DataMember(Name = "labels", IsRequired = true, EmitDefaultValue = true)]
        public List<Report> Labels { get; set; }

        /// <summary>
        /// Static ZPL findings: structure, encoding, bounds
        /// </summary>
        /// <value>Static ZPL findings: structure, encoding, bounds</value>
        [DataMember(Name = "lint", IsRequired = true, EmitDefaultValue = true)]
        public List<Finding> Lint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreflightOutputBody {\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Lint: ").Append(Lint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
