/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// PrinterBody
    /// </summary>
    [DataContract(Name = "PrinterBody")]
    public partial class PrinterBody : IValidatableObject
    {
        /// <summary>
        /// Defines Mode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Ephemeral for value: ephemeral
            /// </summary>
            [EnumMember(Value = "ephemeral")]
            Ephemeral = 1,

            /// <summary>
            /// Enum Persistent for value: persistent
            /// </summary>
            [EnumMember(Value = "persistent")]
            Persistent = 2
        }


        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [DataMember(Name = "mode", IsRequired = true, EmitDefaultValue = true)]
        public ModeEnum Mode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PrinterBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PrinterBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PrinterBody" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="dpmm">dpmm (required).</param>
        /// <param name="expiresAt">expiresAt.</param>
        /// <param name="heightMm">heightMm (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="ingestUrl">HTTPS print capability URL. Only returned on creation..</param>
        /// <param name="mode">mode (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="state">state.</param>
        /// <param name="tcp">tcp (required).</param>
        /// <param name="webhookSecret">HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation..</param>
        /// <param name="webhookUrl">webhookUrl.</param>
        /// <param name="widthMm">widthMm (required).</param>
        public PrinterBody(DateTime createdAt = default, long dpmm = default, DateTime expiresAt = default, double heightMm = default, string id = default, string ingestUrl = default, ModeEnum mode = default, string name = default, StatusSnapshot state = default, PrinterBodyTCPStruct tcp = default, string webhookSecret = default, string webhookUrl = default, double widthMm = default)
        {
            this.CreatedAt = createdAt;
            this.Dpmm = dpmm;
            this.HeightMm = heightMm;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PrinterBody and cannot be null");
            }
            this.Id = id;
            this.Mode = mode;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PrinterBody and cannot be null");
            }
            this.Name = name;
            // to ensure "tcp" is required (not null)
            if (tcp == null)
            {
                throw new ArgumentNullException("tcp is a required property for PrinterBody and cannot be null");
            }
            this.Tcp = tcp;
            this.WidthMm = widthMm;
            this.ExpiresAt = expiresAt;
            this.IngestUrl = ingestUrl;
            this.State = state;
            this.WebhookSecret = webhookSecret;
            this.WebhookUrl = webhookUrl;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Dpmm
        /// </summary>
        [DataMember(Name = "dpmm", IsRequired = true, EmitDefaultValue = true)]
        public long Dpmm { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expiresAt", EmitDefaultValue = false)]
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets HeightMm
        /// </summary>
        [DataMember(Name = "heightMm", IsRequired = true, EmitDefaultValue = true)]
        public double HeightMm { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// HTTPS print capability URL. Only returned on creation.
        /// </summary>
        /// <value>HTTPS print capability URL. Only returned on creation.</value>
        [DataMember(Name = "ingestUrl", EmitDefaultValue = false)]
        public string IngestUrl { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StatusSnapshot State { get; set; }

        /// <summary>
        /// Gets or Sets Tcp
        /// </summary>
        [DataMember(Name = "tcp", IsRequired = true, EmitDefaultValue = true)]
        public PrinterBodyTCPStruct Tcp { get; set; }

        /// <summary>
        /// HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation.
        /// </summary>
        /// <value>HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation.</value>
        [DataMember(Name = "webhookSecret", EmitDefaultValue = false)]
        public string WebhookSecret { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [DataMember(Name = "webhookUrl", EmitDefaultValue = false)]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Gets or Sets WidthMm
        /// </summary>
        [DataMember(Name = "widthMm", IsRequired = true, EmitDefaultValue = true)]
        public double WidthMm { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrinterBody {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Dpmm: ").Append(Dpmm).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  HeightMm: ").Append(HeightMm).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IngestUrl: ").Append(IngestUrl).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Tcp: ").Append(Tcp).Append("\n");
            sb.Append("  WebhookSecret: ").Append(WebhookSecret).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  WidthMm: ").Append(WidthMm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
