/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// RenderInputBody
    /// </summary>
    [DataContract(Name = "RenderInputBody")]
    public partial class RenderInputBody : IValidatableObject
    {
        /// <summary>
        /// Print density in dots/mm (152/203/300/600 dpi); default 8
        /// </summary>
        /// <value>Print density in dots/mm (152/203/300/600 dpi); default 8</value>
        public enum DpmmEnum : long
        {
            /// <summary>
            /// Enum NUMBER_6 for value: 6
            /// </summary>
            NUMBER_6 = 6,

            /// <summary>
            /// Enum NUMBER_8 for value: 8
            /// </summary>
            NUMBER_8 = 8,

            /// <summary>
            /// Enum NUMBER_12 for value: 12
            /// </summary>
            NUMBER_12 = 12,

            /// <summary>
            /// Enum NUMBER_24 for value: 24
            /// </summary>
            NUMBER_24 = 24
        }


        /// <summary>
        /// Print density in dots/mm (152/203/300/600 dpi); default 8
        /// </summary>
        /// <value>Print density in dots/mm (152/203/300/600 dpi); default 8</value>
        [DataMember(Name = "dpmm", EmitDefaultValue = false)]
        public DpmmEnum? Dpmm { get; set; }
        /// <summary>
        /// Named label size in inches; alternative to widthMm/heightMm
        /// </summary>
        /// <value>Named label size in inches; alternative to widthMm/heightMm</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PresetEnum
        {
            /// <summary>
            /// Enum _4x6 for value: 4x6
            /// </summary>
            [EnumMember(Value = "4x6")]
            _4x6 = 1,

            /// <summary>
            /// Enum _6x4 for value: 6x4
            /// </summary>
            [EnumMember(Value = "6x4")]
            _6x4 = 2,

            /// <summary>
            /// Enum _4x4 for value: 4x4
            /// </summary>
            [EnumMember(Value = "4x4")]
            _4x4 = 3,

            /// <summary>
            /// Enum _4x2 for value: 4x2
            /// </summary>
            [EnumMember(Value = "4x2")]
            _4x2 = 4,

            /// <summary>
            /// Enum _2x4 for value: 2x4
            /// </summary>
            [EnumMember(Value = "2x4")]
            _2x4 = 5,

            /// <summary>
            /// Enum _3x5 for value: 3x5
            /// </summary>
            [EnumMember(Value = "3x5")]
            _3x5 = 6,

            /// <summary>
            /// Enum _5x3 for value: 5x3
            /// </summary>
            [EnumMember(Value = "5x3")]
            _5x3 = 7,

            /// <summary>
            /// Enum _2x3 for value: 2x3
            /// </summary>
            [EnumMember(Value = "2x3")]
            _2x3 = 8,

            /// <summary>
            /// Enum _3x2 for value: 3x2
            /// </summary>
            [EnumMember(Value = "3x2")]
            _3x2 = 9,

            /// <summary>
            /// Enum Netstamp for value: netstamp
            /// </summary>
            [EnumMember(Value = "netstamp")]
            Netstamp = 10,

            /// <summary>
            /// Enum _225x125 for value: 2.25x1.25
            /// </summary>
            [EnumMember(Value = "2.25x1.25")]
            _225x125 = 11,

            /// <summary>
            /// Enum _15x1 for value: 1.5x1
            /// </summary>
            [EnumMember(Value = "1.5x1")]
            _15x1 = 12,

            /// <summary>
            /// Enum _2x1 for value: 2x1
            /// </summary>
            [EnumMember(Value = "2x1")]
            _2x1 = 13,

            /// <summary>
            /// Enum _3x1 for value: 3x1
            /// </summary>
            [EnumMember(Value = "3x1")]
            _3x1 = 14,

            /// <summary>
            /// Enum _4x1 for value: 4x1
            /// </summary>
            [EnumMember(Value = "4x1")]
            _4x1 = 15,

            /// <summary>
            /// Enum _1x1 for value: 1x1
            /// </summary>
            [EnumMember(Value = "1x1")]
            _1x1 = 16,

            /// <summary>
            /// Enum _4x3 for value: 4x3
            /// </summary>
            [EnumMember(Value = "4x3")]
            _4x3 = 17,

            /// <summary>
            /// Enum _4x8 for value: 4x8
            /// </summary>
            [EnumMember(Value = "4x8")]
            _4x8 = 18,

            /// <summary>
            /// Enum A6 for value: a6
            /// </summary>
            [EnumMember(Value = "a6")]
            A6 = 19
        }


        /// <summary>
        /// Named label size in inches; alternative to widthMm/heightMm
        /// </summary>
        /// <value>Named label size in inches; alternative to widthMm/heightMm</value>
        [DataMember(Name = "preset", EmitDefaultValue = false)]
        public PresetEnum? Preset { get; set; }
        /// <summary>
        /// Defines Rotation
        /// </summary>
        public enum RotationEnum : long
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_90 for value: 90
            /// </summary>
            NUMBER_90 = 90,

            /// <summary>
            /// Enum NUMBER_180 for value: 180
            /// </summary>
            NUMBER_180 = 180,

            /// <summary>
            /// Enum NUMBER_270 for value: 270
            /// </summary>
            NUMBER_270 = 270
        }


        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>
        [DataMember(Name = "rotation", EmitDefaultValue = false)]
        public RotationEnum? Rotation { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderInputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RenderInputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderInputBody" /> class.
        /// </summary>
        /// <param name="dpmm">Print density in dots/mm (152/203/300/600 dpi); default 8.</param>
        /// <param name="heightMm">heightMm.</param>
        /// <param name="preset">Named label size in inches; alternative to widthMm/heightMm.</param>
        /// <param name="rotation">rotation.</param>
        /// <param name="widthMm">widthMm.</param>
        /// <param name="zpl">zpl (required).</param>
        public RenderInputBody(DpmmEnum? dpmm = default, double heightMm = default, PresetEnum? preset = default, RotationEnum? rotation = default, double widthMm = default, string zpl = default)
        {
            // to ensure "zpl" is required (not null)
            if (zpl == null)
            {
                throw new ArgumentNullException("zpl is a required property for RenderInputBody and cannot be null");
            }
            this.Zpl = zpl;
            this.Dpmm = dpmm;
            this.HeightMm = heightMm;
            this.Preset = preset;
            this.Rotation = rotation;
            this.WidthMm = widthMm;
        }

        /// <summary>
        /// Gets or Sets HeightMm
        /// </summary>
        [DataMember(Name = "heightMm", EmitDefaultValue = false)]
        public double HeightMm { get; set; }

        /// <summary>
        /// Gets or Sets WidthMm
        /// </summary>
        [DataMember(Name = "widthMm", EmitDefaultValue = false)]
        public double WidthMm { get; set; }

        /// <summary>
        /// Gets or Sets Zpl
        /// </summary>
        [DataMember(Name = "zpl", IsRequired = true, EmitDefaultValue = true)]
        public string Zpl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenderInputBody {\n");
            sb.Append("  Dpmm: ").Append(Dpmm).Append("\n");
            sb.Append("  HeightMm: ").Append(HeightMm).Append("\n");
            sb.Append("  Preset: ").Append(Preset).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  WidthMm: ").Append(WidthMm).Append("\n");
            sb.Append("  Zpl: ").Append(Zpl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // HeightMm (double) minimum
            if (this.HeightMm < (double)0)
            {
                yield return new ValidationResult("Invalid value for HeightMm, must be a value greater than or equal to 0.", new [] { "HeightMm" });
            }

            // WidthMm (double) minimum
            if (this.WidthMm < (double)0)
            {
                yield return new ValidationResult("Invalid value for WidthMm, must be a value greater than or equal to 0.", new [] { "WidthMm" });
            }

            yield break;
        }
    }

}
