/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// RenderOutputBody
    /// </summary>
    [DataContract(Name = "RenderOutputBody")]
    public partial class RenderOutputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderOutputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RenderOutputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderOutputBody" /> class.
        /// </summary>
        /// <param name="labelCount">labelCount (required).</param>
        /// <param name="labels">labels (required).</param>
        public RenderOutputBody(long labelCount = default, List<RenderedLabel> labels = default)
        {
            this.LabelCount = labelCount;
            // to ensure "labels" is required (not null)
            if (labels == null)
            {
                throw new ArgumentNullException("labels is a required property for RenderOutputBody and cannot be null");
            }
            this.Labels = labels;
        }

        /// <summary>
        /// Gets or Sets LabelCount
        /// </summary>
        [DataMember(Name = "labelCount", IsRequired = true, EmitDefaultValue = true)]
        public long LabelCount { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name = "labels", IsRequired = true, EmitDefaultValue = true)]
        public List<RenderedLabel> Labels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenderOutputBody {\n");
            sb.Append("  LabelCount: ").Append(LabelCount).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
