/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// Report
    /// </summary>
    [DataContract(Name = "Report")]
    public partial class Report : IValidatableObject
    {
        /// <summary>
        /// Worst status across all checks
        /// </summary>
        /// <value>Worst status across all checks</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GradeEnum
        {
            /// <summary>
            /// Enum Pass for value: pass
            /// </summary>
            [EnumMember(Value = "pass")]
            Pass = 1,

            /// <summary>
            /// Enum Warn for value: warn
            /// </summary>
            [EnumMember(Value = "warn")]
            Warn = 2,

            /// <summary>
            /// Enum Fail for value: fail
            /// </summary>
            [EnumMember(Value = "fail")]
            Fail = 3
        }


        /// <summary>
        /// Worst status across all checks
        /// </summary>
        /// <value>Worst status across all checks</value>
        [DataMember(Name = "grade", IsRequired = true, EmitDefaultValue = true)]
        public GradeEnum Grade { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Report" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Report() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Report" /> class.
        /// </summary>
        /// <param name="barcodes">barcodes (required).</param>
        /// <param name="grade">Worst status across all checks (required).</param>
        /// <param name="warnings">Label-level notes, e.g. no barcodes found.</param>
        public Report(List<Barcode> barcodes = default, GradeEnum grade = default, List<string> warnings = default)
        {
            // to ensure "barcodes" is required (not null)
            if (barcodes == null)
            {
                throw new ArgumentNullException("barcodes is a required property for Report and cannot be null");
            }
            this.Barcodes = barcodes;
            this.Grade = grade;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Gets or Sets Barcodes
        /// </summary>
        [DataMember(Name = "barcodes", IsRequired = true, EmitDefaultValue = true)]
        public List<Barcode> Barcodes { get; set; }

        /// <summary>
        /// Label-level notes, e.g. no barcodes found
        /// </summary>
        /// <value>Label-level notes, e.g. no barcodes found</value>
        [DataMember(Name = "warnings", EmitDefaultValue = true)]
        public List<string> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Report {\n");
            sb.Append("  Barcodes: ").Append(Barcodes).Append("\n");
            sb.Append("  Grade: ").Append(Grade).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
