/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// StampInputBody
    /// </summary>
    [DataContract(Name = "StampInputBody")]
    public partial class StampInputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StampInputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StampInputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StampInputBody" /> class.
        /// </summary>
        /// <param name="image">PNG/GIF/JPEG, base64-encoded (required).</param>
        /// <param name="widthDots">Stamp width in dots; 0 keeps the image&#39;s natural size.</param>
        /// <param name="x">Left edge in dots.</param>
        /// <param name="y">Top edge in dots.</param>
        /// <param name="zpl">zpl (required).</param>
        public StampInputBody(string image = default, long widthDots = default, long x = default, long y = default, string zpl = default)
        {
            // to ensure "image" is required (not null)
            if (image == null)
            {
                throw new ArgumentNullException("image is a required property for StampInputBody and cannot be null");
            }
            this.Image = image;
            // to ensure "zpl" is required (not null)
            if (zpl == null)
            {
                throw new ArgumentNullException("zpl is a required property for StampInputBody and cannot be null");
            }
            this.Zpl = zpl;
            this.WidthDots = widthDots;
            this.X = x;
            this.Y = y;
        }

        /// <summary>
        /// PNG/GIF/JPEG, base64-encoded
        /// </summary>
        /// <value>PNG/GIF/JPEG, base64-encoded</value>
        [DataMember(Name = "image", IsRequired = true, EmitDefaultValue = true)]
        public string Image { get; set; }

        /// <summary>
        /// Stamp width in dots; 0 keeps the image&#39;s natural size
        /// </summary>
        /// <value>Stamp width in dots; 0 keeps the image&#39;s natural size</value>
        [DataMember(Name = "widthDots", EmitDefaultValue = false)]
        public long WidthDots { get; set; }

        /// <summary>
        /// Left edge in dots
        /// </summary>
        /// <value>Left edge in dots</value>
        [DataMember(Name = "x", EmitDefaultValue = false)]
        public long X { get; set; }

        /// <summary>
        /// Top edge in dots
        /// </summary>
        /// <value>Top edge in dots</value>
        [DataMember(Name = "y", EmitDefaultValue = false)]
        public long Y { get; set; }

        /// <summary>
        /// Gets or Sets Zpl
        /// </summary>
        [DataMember(Name = "zpl", IsRequired = true, EmitDefaultValue = true)]
        public string Zpl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StampInputBody {\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  WidthDots: ").Append(WidthDots).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("  Zpl: ").Append(Zpl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // WidthDots (long) minimum
            if (this.WidthDots < (long)0)
            {
                yield return new ValidationResult("Invalid value for WidthDots, must be a value greater than or equal to 0.", new [] { "WidthDots" });
            }

            // X (long) minimum
            if (this.X < (long)0)
            {
                yield return new ValidationResult("Invalid value for X, must be a value greater than or equal to 0.", new [] { "X" });
            }

            // Y (long) minimum
            if (this.Y < (long)0)
            {
                yield return new ValidationResult("Invalid value for Y, must be a value greater than or equal to 0.", new [] { "Y" });
            }

            yield break;
        }
    }

}
