/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// StatusSnapshot
    /// </summary>
    [DataContract(Name = "StatusSnapshot")]
    public partial class StatusSnapshot : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatusSnapshot" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StatusSnapshot() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StatusSnapshot" /> class.
        /// </summary>
        /// <param name="darkness">print.tone setting, e.g. 20.0 (required).</param>
        /// <param name="faults">faults (required).</param>
        /// <param name="formatsInBuffer">formatsInBuffer (required).</param>
        /// <param name="friendlyName">device.friendly_name override; empty means unset (required).</param>
        /// <param name="labelLengthDots">labelLengthDots (required).</param>
        /// <param name="odometer">odometer (required).</param>
        /// <param name="queue">queue (required).</param>
        /// <param name="speedIps">media.speed setting, inches/second (required).</param>
        /// <param name="supplies">What is left on the roll; zero loaded means endless (required).</param>
        /// <param name="tearOff">ezpl.tear_off setting, dots (required).</param>
        /// <param name="widthDots">widthDots (required).</param>
        public StatusSnapshot(string darkness = default, Faults faults = default, long formatsInBuffer = default, string friendlyName = default, long labelLengthDots = default, long odometer = default, List<HeldJob> queue = default, string speedIps = default, Supplies supplies = default, string tearOff = default, long widthDots = default)
        {
            // to ensure "darkness" is required (not null)
            if (darkness == null)
            {
                throw new ArgumentNullException("darkness is a required property for StatusSnapshot and cannot be null");
            }
            this.Darkness = darkness;
            // to ensure "faults" is required (not null)
            if (faults == null)
            {
                throw new ArgumentNullException("faults is a required property for StatusSnapshot and cannot be null");
            }
            this.Faults = faults;
            this.FormatsInBuffer = formatsInBuffer;
            // to ensure "friendlyName" is required (not null)
            if (friendlyName == null)
            {
                throw new ArgumentNullException("friendlyName is a required property for StatusSnapshot and cannot be null");
            }
            this.FriendlyName = friendlyName;
            this.LabelLengthDots = labelLengthDots;
            this.Odometer = odometer;
            // to ensure "queue" is required (not null)
            if (queue == null)
            {
                throw new ArgumentNullException("queue is a required property for StatusSnapshot and cannot be null");
            }
            this.Queue = queue;
            // to ensure "speedIps" is required (not null)
            if (speedIps == null)
            {
                throw new ArgumentNullException("speedIps is a required property for StatusSnapshot and cannot be null");
            }
            this.SpeedIps = speedIps;
            // to ensure "supplies" is required (not null)
            if (supplies == null)
            {
                throw new ArgumentNullException("supplies is a required property for StatusSnapshot and cannot be null");
            }
            this.Supplies = supplies;
            // to ensure "tearOff" is required (not null)
            if (tearOff == null)
            {
                throw new ArgumentNullException("tearOff is a required property for StatusSnapshot and cannot be null");
            }
            this.TearOff = tearOff;
            this.WidthDots = widthDots;
        }

        /// <summary>
        /// print.tone setting, e.g. 20.0
        /// </summary>
        /// <value>print.tone setting, e.g. 20.0</value>
        [DataMember(Name = "darkness", IsRequired = true, EmitDefaultValue = true)]
        public string Darkness { get; set; }

        /// <summary>
        /// Gets or Sets Faults
        /// </summary>
        [DataMember(Name = "faults", IsRequired = true, EmitDefaultValue = true)]
        public Faults Faults { get; set; }

        /// <summary>
        /// Gets or Sets FormatsInBuffer
        /// </summary>
        [DataMember(Name = "formatsInBuffer", IsRequired = true, EmitDefaultValue = true)]
        public long FormatsInBuffer { get; set; }

        /// <summary>
        /// device.friendly_name override; empty means unset
        /// </summary>
        /// <value>device.friendly_name override; empty means unset</value>
        [DataMember(Name = "friendlyName", IsRequired = true, EmitDefaultValue = true)]
        public string FriendlyName { get; set; }

        /// <summary>
        /// Gets or Sets LabelLengthDots
        /// </summary>
        [DataMember(Name = "labelLengthDots", IsRequired = true, EmitDefaultValue = true)]
        public long LabelLengthDots { get; set; }

        /// <summary>
        /// Gets or Sets Odometer
        /// </summary>
        [DataMember(Name = "odometer", IsRequired = true, EmitDefaultValue = true)]
        public long Odometer { get; set; }

        /// <summary>
        /// Gets or Sets Queue
        /// </summary>
        [DataMember(Name = "queue", IsRequired = true, EmitDefaultValue = true)]
        public List<HeldJob> Queue { get; set; }

        /// <summary>
        /// media.speed setting, inches/second
        /// </summary>
        /// <value>media.speed setting, inches/second</value>
        [DataMember(Name = "speedIps", IsRequired = true, EmitDefaultValue = true)]
        public string SpeedIps { get; set; }

        /// <summary>
        /// What is left on the roll; zero loaded means endless
        /// </summary>
        /// <value>What is left on the roll; zero loaded means endless</value>
        [DataMember(Name = "supplies", IsRequired = true, EmitDefaultValue = true)]
        public Supplies Supplies { get; set; }

        /// <summary>
        /// ezpl.tear_off setting, dots
        /// </summary>
        /// <value>ezpl.tear_off setting, dots</value>
        [DataMember(Name = "tearOff", IsRequired = true, EmitDefaultValue = true)]
        public string TearOff { get; set; }

        /// <summary>
        /// Gets or Sets WidthDots
        /// </summary>
        [DataMember(Name = "widthDots", IsRequired = true, EmitDefaultValue = true)]
        public long WidthDots { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatusSnapshot {\n");
            sb.Append("  Darkness: ").Append(Darkness).Append("\n");
            sb.Append("  Faults: ").Append(Faults).Append("\n");
            sb.Append("  FormatsInBuffer: ").Append(FormatsInBuffer).Append("\n");
            sb.Append("  FriendlyName: ").Append(FriendlyName).Append("\n");
            sb.Append("  LabelLengthDots: ").Append(LabelLengthDots).Append("\n");
            sb.Append("  Odometer: ").Append(Odometer).Append("\n");
            sb.Append("  Queue: ").Append(Queue).Append("\n");
            sb.Append("  SpeedIps: ").Append(SpeedIps).Append("\n");
            sb.Append("  Supplies: ").Append(Supplies).Append("\n");
            sb.Append("  TearOff: ").Append(TearOff).Append("\n");
            sb.Append("  WidthDots: ").Append(WidthDots).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
