/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// StatusSnapshot
    /// </summary>
    [DataContract(Name = "StatusSnapshot")]
    public partial class StatusSnapshot : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatusSnapshot" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StatusSnapshot() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StatusSnapshot" /> class.
        /// </summary>
        /// <param name="faults">faults (required).</param>
        /// <param name="formatsInBuffer">formatsInBuffer (required).</param>
        /// <param name="labelLengthDots">labelLengthDots (required).</param>
        /// <param name="odometer">odometer (required).</param>
        /// <param name="widthDots">widthDots (required).</param>
        public StatusSnapshot(Faults faults = default, long formatsInBuffer = default, long labelLengthDots = default, long odometer = default, long widthDots = default)
        {
            // to ensure "faults" is required (not null)
            if (faults == null)
            {
                throw new ArgumentNullException("faults is a required property for StatusSnapshot and cannot be null");
            }
            this.Faults = faults;
            this.FormatsInBuffer = formatsInBuffer;
            this.LabelLengthDots = labelLengthDots;
            this.Odometer = odometer;
            this.WidthDots = widthDots;
        }

        /// <summary>
        /// Gets or Sets Faults
        /// </summary>
        [DataMember(Name = "faults", IsRequired = true, EmitDefaultValue = true)]
        public Faults Faults { get; set; }

        /// <summary>
        /// Gets or Sets FormatsInBuffer
        /// </summary>
        [DataMember(Name = "formatsInBuffer", IsRequired = true, EmitDefaultValue = true)]
        public long FormatsInBuffer { get; set; }

        /// <summary>
        /// Gets or Sets LabelLengthDots
        /// </summary>
        [DataMember(Name = "labelLengthDots", IsRequired = true, EmitDefaultValue = true)]
        public long LabelLengthDots { get; set; }

        /// <summary>
        /// Gets or Sets Odometer
        /// </summary>
        [DataMember(Name = "odometer", IsRequired = true, EmitDefaultValue = true)]
        public long Odometer { get; set; }

        /// <summary>
        /// Gets or Sets WidthDots
        /// </summary>
        [DataMember(Name = "widthDots", IsRequired = true, EmitDefaultValue = true)]
        public long WidthDots { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatusSnapshot {\n");
            sb.Append("  Faults: ").Append(Faults).Append("\n");
            sb.Append("  FormatsInBuffer: ").Append(FormatsInBuffer).Append("\n");
            sb.Append("  LabelLengthDots: ").Append(LabelLengthDots).Append("\n");
            sb.Append("  Odometer: ").Append(Odometer).Append("\n");
            sb.Append("  WidthDots: ").Append(WidthDots).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
