/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// Supplies
    /// </summary>
    [DataContract(Name = "Supplies")]
    public partial class Supplies : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Supplies" /> class.
        /// </summary>
        /// <param name="labelsLeft">Labels left on the roll.</param>
        /// <param name="labelsLoaded">Labels the roll held when it was fitted; 0 means an endless roll.</param>
        /// <param name="ribbonMmLeft">Millimetres of ribbon left.</param>
        /// <param name="ribbonMmLoaded">Millimetres of ribbon fitted; 0 means endless, which is also what direct thermal looks like.</param>
        public Supplies(long labelsLeft = default, long labelsLoaded = default, long ribbonMmLeft = default, long ribbonMmLoaded = default)
        {
            this.LabelsLeft = labelsLeft;
            this.LabelsLoaded = labelsLoaded;
            this.RibbonMmLeft = ribbonMmLeft;
            this.RibbonMmLoaded = ribbonMmLoaded;
        }

        /// <summary>
        /// Labels left on the roll
        /// </summary>
        /// <value>Labels left on the roll</value>
        [DataMember(Name = "labelsLeft", EmitDefaultValue = false)]
        public long LabelsLeft { get; set; }

        /// <summary>
        /// Labels the roll held when it was fitted; 0 means an endless roll
        /// </summary>
        /// <value>Labels the roll held when it was fitted; 0 means an endless roll</value>
        [DataMember(Name = "labelsLoaded", EmitDefaultValue = false)]
        public long LabelsLoaded { get; set; }

        /// <summary>
        /// Millimetres of ribbon left
        /// </summary>
        /// <value>Millimetres of ribbon left</value>
        [DataMember(Name = "ribbonMmLeft", EmitDefaultValue = false)]
        public long RibbonMmLeft { get; set; }

        /// <summary>
        /// Millimetres of ribbon fitted; 0 means endless, which is also what direct thermal looks like
        /// </summary>
        /// <value>Millimetres of ribbon fitted; 0 means endless, which is also what direct thermal looks like</value>
        [DataMember(Name = "ribbonMmLoaded", EmitDefaultValue = false)]
        public long RibbonMmLoaded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Supplies {\n");
            sb.Append("  LabelsLeft: ").Append(LabelsLeft).Append("\n");
            sb.Append("  LabelsLoaded: ").Append(LabelsLoaded).Append("\n");
            sb.Append("  RibbonMmLeft: ").Append(RibbonMmLeft).Append("\n");
            sb.Append("  RibbonMmLoaded: ").Append(RibbonMmLoaded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
