/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// UpdatePrinterInputBody
    /// </summary>
    [DataContract(Name = "UpdatePrinterInputBody")]
    public partial class UpdatePrinterInputBody : IValidatableObject
    {
        /// <summary>
        /// Defines AccessMode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AccessModeEnum
        {
            /// <summary>
            /// Enum Open for value: open
            /// </summary>
            [EnumMember(Value = "open")]
            Open = 1,

            /// <summary>
            /// Enum Token for value: token
            /// </summary>
            [EnumMember(Value = "token")]
            Token = 2,

            /// <summary>
            /// Enum Ip for value: ip
            /// </summary>
            [EnumMember(Value = "ip")]
            Ip = 3
        }


        /// <summary>
        /// Gets or Sets AccessMode
        /// </summary>
        [DataMember(Name = "accessMode", EmitDefaultValue = false)]
        public AccessModeEnum? AccessMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePrinterInputBody" /> class.
        /// </summary>
        /// <param name="accessMode">accessMode.</param>
        /// <param name="anonymize">anonymize.</param>
        /// <param name="name">name.</param>
        /// <param name="webhookUrl">webhookUrl.</param>
        public UpdatePrinterInputBody(AccessModeEnum? accessMode = default, bool anonymize = default, string name = default, string webhookUrl = default)
        {
            this.AccessMode = accessMode;
            this.Anonymize = anonymize;
            this.Name = name;
            this.WebhookUrl = webhookUrl;
        }

        /// <summary>
        /// Gets or Sets Anonymize
        /// </summary>
        [DataMember(Name = "anonymize", EmitDefaultValue = true)]
        public bool Anonymize { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets WebhookUrl
        /// </summary>
        [DataMember(Name = "webhookUrl", EmitDefaultValue = false)]
        public string WebhookUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdatePrinterInputBody {\n");
            sb.Append("  AccessMode: ").Append(AccessMode).Append("\n");
            sb.Append("  Anonymize: ").Append(Anonymize).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
