/*
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StripyHorse.Client.OpenAPIDateConverter;

namespace StripyHorse.Model
{
    /// <summary>
    /// ZplHTMLInputBody
    /// </summary>
    [DataContract(Name = "ZplHTMLInputBody")]
    public partial class ZplHTMLInputBody : IValidatableObject
    {
        /// <summary>
        /// Print density in dots/mm (152/203/300/600 dpi); default 8
        /// </summary>
        /// <value>Print density in dots/mm (152/203/300/600 dpi); default 8</value>
        public enum DpmmEnum : long
        {
            /// <summary>
            /// Enum NUMBER_6 for value: 6
            /// </summary>
            NUMBER_6 = 6,

            /// <summary>
            /// Enum NUMBER_8 for value: 8
            /// </summary>
            NUMBER_8 = 8,

            /// <summary>
            /// Enum NUMBER_12 for value: 12
            /// </summary>
            NUMBER_12 = 12,

            /// <summary>
            /// Enum NUMBER_24 for value: 24
            /// </summary>
            NUMBER_24 = 24
        }


        /// <summary>
        /// Print density in dots/mm (152/203/300/600 dpi); default 8
        /// </summary>
        /// <value>Print density in dots/mm (152/203/300/600 dpi); default 8</value>
        [DataMember(Name = "dpmm", EmitDefaultValue = false)]
        public DpmmEnum? Dpmm { get; set; }
        /// <summary>
        /// Named label size in inches; alternative to widthMm/heightMm
        /// </summary>
        /// <value>Named label size in inches; alternative to widthMm/heightMm</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PresetEnum
        {
            /// <summary>
            /// Enum _4x6 for value: 4x6
            /// </summary>
            [EnumMember(Value = "4x6")]
            _4x6 = 1,

            /// <summary>
            /// Enum _6x4 for value: 6x4
            /// </summary>
            [EnumMember(Value = "6x4")]
            _6x4 = 2,

            /// <summary>
            /// Enum _4x4 for value: 4x4
            /// </summary>
            [EnumMember(Value = "4x4")]
            _4x4 = 3,

            /// <summary>
            /// Enum _4x2 for value: 4x2
            /// </summary>
            [EnumMember(Value = "4x2")]
            _4x2 = 4,

            /// <summary>
            /// Enum _2x4 for value: 2x4
            /// </summary>
            [EnumMember(Value = "2x4")]
            _2x4 = 5,

            /// <summary>
            /// Enum _3x5 for value: 3x5
            /// </summary>
            [EnumMember(Value = "3x5")]
            _3x5 = 6,

            /// <summary>
            /// Enum _5x3 for value: 5x3
            /// </summary>
            [EnumMember(Value = "5x3")]
            _5x3 = 7
        }


        /// <summary>
        /// Named label size in inches; alternative to widthMm/heightMm
        /// </summary>
        /// <value>Named label size in inches; alternative to widthMm/heightMm</value>
        [DataMember(Name = "preset", EmitDefaultValue = false)]
        public PresetEnum? Preset { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ZplHTMLInputBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ZplHTMLInputBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ZplHTMLInputBody" /> class.
        /// </summary>
        /// <param name="dpmm">Print density in dots/mm (152/203/300/600 dpi); default 8.</param>
        /// <param name="heightMm">heightMm.</param>
        /// <param name="preset">Named label size in inches; alternative to widthMm/heightMm.</param>
        /// <param name="widthMm">widthMm.</param>
        /// <param name="zpl">zpl (required).</param>
        public ZplHTMLInputBody(DpmmEnum? dpmm = default, double heightMm = default, PresetEnum? preset = default, double widthMm = default, string zpl = default)
        {
            // to ensure "zpl" is required (not null)
            if (zpl == null)
            {
                throw new ArgumentNullException("zpl is a required property for ZplHTMLInputBody and cannot be null");
            }
            this.Zpl = zpl;
            this.Dpmm = dpmm;
            this.HeightMm = heightMm;
            this.Preset = preset;
            this.WidthMm = widthMm;
        }

        /// <summary>
        /// Gets or Sets HeightMm
        /// </summary>
        [DataMember(Name = "heightMm", EmitDefaultValue = false)]
        public double HeightMm { get; set; }

        /// <summary>
        /// Gets or Sets WidthMm
        /// </summary>
        [DataMember(Name = "widthMm", EmitDefaultValue = false)]
        public double WidthMm { get; set; }

        /// <summary>
        /// Gets or Sets Zpl
        /// </summary>
        [DataMember(Name = "zpl", IsRequired = true, EmitDefaultValue = true)]
        public string Zpl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZplHTMLInputBody {\n");
            sb.Append("  Dpmm: ").Append(Dpmm).Append("\n");
            sb.Append("  HeightMm: ").Append(HeightMm).Append("\n");
            sb.Append("  Preset: ").Append(Preset).Append("\n");
            sb.Append("  WidthMm: ").Append(WidthMm).Append("\n");
            sb.Append("  Zpl: ").Append(Zpl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // HeightMm (double) minimum
            if (this.HeightMm < (double)0)
            {
                yield return new ValidationResult("Invalid value for HeightMm, must be a value greater than or equal to 0.", new [] { "HeightMm" });
            }

            // WidthMm (double) minimum
            if (this.WidthMm < (double)0)
            {
                yield return new ValidationResult("Invalid value for WidthMm, must be a value greater than or equal to 0.", new [] { "WidthMm" });
            }

            yield break;
        }
    }

}
